### ISSUE TITLE
SimplePicker doesn’t work correctly: it is impossible to choose the last item!

### ISSUE THREAD

**Issue by andrakula** [Alfresco/Aikau#1011]
I try it on the Aikau Sandpit.

**Comment by draperd** [comment]
There isn't a SimplePicker example in the Sandpit, there is however a unit test page and a unit test for it (if you build and run the unit test application following the instructions linked from the home page of the Aikau GitHub project you'll be able to access the test page at this URL: http://localhost:8089/aikau/page/tp/ws/SimplePicker)

I've tested it manually, it works fine - you can choose the last item. I'm closing this issue.

**Comment by andrakula** [comment]
SimplePicker didn't work with Alfresco 5.0.3 by my local environment. And then I used Sandpit to create a simple SimplePicker (see a screenshot). The last available item can not be picked.

![bildschirmfoto 2016-04-21 um 13 37 29](https://cloud.githubusercontent.com/assets/7724548/14707776/bd042b12-07c6-11e6-9480-75fa3292a252.png)

`[
	{
		"name" : "alfresco/forms/controls/SimplePicker",
		"config" : {
			"label" : "Pick Some items",
			"description" : "This is a simple picker with some hard-coded data",
			"name" : "hardcoded",
			"reorderable" : true,
			"currentData" : {
			"items" : [ {
					"name" : "One"
				}, {
					"name" : "Two"
				}, {
					"name" : "Three"
			} ]
			}
		}
	}
]`
