### ISSUE TITLE
Nullpointerexception at login

### ISSUE THREAD

**Issue by tomsnijkers** [Alfresco/Aikau#1044]
When I build the latest version of the AikauSample project with maven, I get a nullpointerexception from the jetty server.

**Comment by draperd** [comment]
What version of Aikau? Is this the same problem as #1033 ?

**Comment by tomsnijkers** [comment]
I tried 1.0.67 and 1.0.65, both had this issue. The solution from #1033 does work. My apologies for creating this double issue. Thanks for the quick reply!
