### ISSUE TITLE
ManageAspectService with custom i18n messages

### ISSUE THREAD

**Issue by vincent-kali** [Alfresco/Aikau#1081]
When I set in manageAspectService the following config to override the standard i18n messages, the configuration is just ignored:
......
{
		name: "alfresco/services/actions/ManageAspectsService",
		config: {
		availableAspects: getMyAvailableAspects(...),
		addableAspects: getMyAddableAspects(...),
		removableAspects: getMyRemovableAspects(...),
		i18nRequirements: [{i18nFile: "myWidgets/i18n/ManageAspectsService.properties"}],
        }
    },
.......
'myWidgets' is correcly declared and I use these widgets in the current page.
Is this a bug or did I misunderstand this configuration option ?

**Comment by draperd** [comment]
The i18nRequiresments is only applicable when used within the source code of a module - Surf does not analyse the config model, only the source code. However, it is possible to just include localization properties in the .get.properties file of the WebScript itself.
