### ISSUE TITLE
Paginator + Hash + BreadcrumbTrail behaviour

### ISSUE THREAD

**Issue by aviriel** [Alfresco/Aikau#1082]
When using `alfresco/documentlibrary/AlfBreadcrumbTrail` together with `alfresco/lists/Paginator`, incorrent page number is used when going back using breadcrumb.

Way to reproduce:
```
{
  name: "alfresco/documentlibrary/AlfBreadcrumbTrail",
  config: {
    rawData: true,
    useHash: true
  }
},
{
  name: "alfresco/lists/Paginator",
  config: {
    documentsPerPage: 5,
    pageSizes: [3,5,10]
  }
},
{
  name: "alfresco/documentlibrary/AlfDocumentList",
  config: {
    rootNode: "alfresco://user/home",
    rawData: true,
    usePagination: true,
    useHash: true,
    widgets: [
      {
        name: "alfresco/documentlibrary/views/AlfSimpleView"
      }
    ]
  }
}
```
Go to the not-first page (3rd page in Data Dictionary for example), then click to the breadcrumb to go up. 
Expected behaviour: the first page of root folder opens. URL should become `http://localhost:8090/aikau-sample/page/ap/ws/home#path=%2F&currentPage=1`
Real behaviour: the same page of the root folder opens (that means that unexistent page tries to open and user sees empty doclist, that is not true. URL is `http://localhost:8090/aikau-sample/page/ap/ws/home#path=%2F&currentPage=3`

The same can be tested with (rawData: false). Without "useHash: true" works good.

**Comment by draperd** [comment]
Because this was such a small fix, I've included it in the 1.0.69 release which is now available.
