### ISSUE TITLE
Workaround for AKU-749 makes it hard to customize label

### ISSUE THREAD

**Issue by AFaust** [Alfresco/Aikau#1090]
The workaround for AKU-749 (#730) introduced a faceted-search specific message in the message bundle for the alfresco/html/Label widget, that is not easily customizable.  The widget itself doesn't even use the label, instead the AlfSearchList uses it to externally provide a rendered text to a label. For a customer use case I was trying to customize that message as usual, by overriding its value in the message bundle of the page web script. Unfortunately, message bundles provided by widgets (defaultScope) always take precedent over page web script ones (pageScope).

The only way I currently see me able to customize ```faceted-search.results-menu.results-found-patch``` is by extending the AlfSearchList widget, using a custom i18nScope for that module and bootstrapping a i18nDependency of that new module into the scope. Strangely enough I am customizing a widget that is not even showing the label that I want customized, which feels very, very wrong.

Generally speaking there should be a simple way that allows to override widget provided labels without requiring widget extension. Yes, when those customizations are meant to be reusable, they should be implemented via custom widget modules, but requiring/forcing it does not help acceptance.

**Comment by AFaust** [comment]
A very simple change to alfresco/core/Core could introduce an optional config parameter to specify a list of messageIds that must be loaded from a specific scope type.
Alternatively, the general lookup order could be configurable, including options for short-circuit handling, e.g. if something was already resolved in first lookup (i.e. pageScope) don't override with lookup from defaultScope.

**Comment by AFaust** [comment]
Additionally, it might be better to enhance the alfresco/html/Label widget to construct the final rendered text itself using some sort of payload to message-parameter-index mapping.

**Comment by draperd** [comment]
I agree that this was a sub-optimal fix. A better solution in my opinion would just be to make the message key configurable in the AlfSearchList (as we do in a number of other widgets).

That would allow a customization to reference a key that could exist in just the WebScript and not require any custom modules. I should have recognized this at the time and abstracted that message key to a configurable attribute.

There is already some support for scoping message ids (using the i18nScope attribute in widgets) but this does not go as far as you suggest. It was added very early on to allow widgets to share message keys but we did not find it especially useful in practice.

**Comment by AFaust** [comment]
For anyone looking at this issue and wondering how to handle the issue of overriding default widget labels (if it wasn't clear from my initial description): I was able to fix my issue (workaround the workaround) with the help of i18nScope. I used
```javascript
// my/workarounds/SearchList
define([ 'dojo/_base/declare', 'alfresco/search/AlfSearchList' ], function(declare, AlfSearchList)
{
    return declare([ AlfSearchList ], {

        i18nRequirements : [ {
            i18nFile : './i18n/SearchList.properties'
        } ],

        i18nScope : 'workaround'
    });
});
```
and included an override to the label in SearchList.properties. Via a customization of the faceted-search JSON model I substituted my workaround SearchList for the standard AlfSearchList widget name. The DojoI18nDeependencyRule will automatically boostrap the SearchList.properties into my custom scope when generating the aggregated JS initialization code, and the widget will prefer any messages from that scope over the pageScope and defaultScope provided ones.

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/AKU-980 to cover this. We have some scope in the current sprint so I'll get something in for tomorrow's 1.0.70 release.

**Comment by draperd** [comment]
As of 1.0.70 it will be possible to customize the AlfSearchList using the `resultsCountMessage` configuration attribute to set an alternative message to be used.

**Comment by draperd** [comment]
1.0.70 is now available.
