### ISSUE TITLE
example PropertyPicker.get.js and PropertyPickerControl

### ISSUE THREAD

**Issue by RedRaccoon** [Alfresco/Aikau#1092]
Hello

I tried to test two example from the aikauTEST
they are in this git folder
[just here](https://github.com/Alfresco/Aikau/tree/5bb954ba95a248e129e4615ad596a9ee406648b0/aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/pickers)

PropertyPicker.get.js doesn't load anything
[When I click on "all" for example](http://www.noelshack.com/2016-23-1465205556-picker1.png)

So I tried the PropertyPickerControl.get.js and even If I was not able to load the payload in the "pickedItem" he seems to "working", [When I click on "all" for example](http://image.noelshack.com/fichiers/2016/23/1465205843-picker2.png)

 so I noticed in the PropertyPickerControl.get.js we call a widget "alfresco/forms/controls/PropertyPicker" who really look like to a new version of the PropertyPicker.get.js

So In my opinion as the example is 1 year old maybe he had to be updated,

for example in the PropertyPicker.get.js the WidgetsForRootPicker, the PropertyPicker config is

```
                                config: {
                                       currentPickerDepth: 1,
                                       url: "api/properties"
                                    }
```

altough in the recent version of [forms/controls/PropertyPicker.js](https://dev.alfresco.com/resource/docs/aikau-jsdoc/PropertyPicker.js.html) it's

```
   config: {
                                       itemsProperty: null,
                                       loadDataPublishTopic: "ALF_CRUD_GET_ALL",
                                       loadDataPublishPayload: {
                                          url: "api/properties"
                                       },
                                       publishPickedItemsToParent: false
                                    }
```

 I tried to do it but still no sucess maybe you have an idea ?

Thank you !

**Comment by RedRaccoon** [comment]
cool writting this helped me to understand that in the "PropertyPickerControl.get.js" we have to add the crud service in the model

```
model.jsonModel = {
   services: [
"alfresco/services/CrudService",
   ],
```

and it's working !!

**Comment by draperd** [comment]
Ah, interestingly that unit test page is not actually used in our unit test suite at all. It appears as though it was brought over when we moved the Aikau code from SVN to GitHub in an unfinished state. As you have spotted there is no services or mocking widgets on the test page to provide data to be displayed. 

I think we should probably remove these files to prevent further confusion.
