### ISSUE TITLE
How to run the tutorial agains a non-local repository?

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/Aikau#113]
I'm trying to run the tutorial on my local machine, but I couldn't find where to configure my remote server's address (my alfresco server runs on a virtual machine, so, no localhost).

Is that possible?

**Comment by draperd** [comment]
Yes, it is possible... just add the following to your tutorial apps surf.xml file (changing IP addresses and ports as necessary):

```XML
<config evaluator="string-compare" condition="Remote">
     <remote>
        <endpoint>
           <id>alfresco-noauth</id>
           <name>Alfresco - unauthenticated access</name>
           <description>Access to Alfresco Repository WebScripts that do not require authentication</description>
           <connector-id>alfresco</connector-id>
           <endpoint-url>http://10.0.2.2:8080/alfresco/s</endpoint-url>
           <identity>none</identity>
        </endpoint>

        <endpoint>
           <id>alfresco</id>
           <name>Alfresco - user access</name>
           <description>Access to Alfresco Repository WebScripts that require user authentication</description>
           <connector-id>alfresco</connector-id>
           <endpoint-url>http://10.0.2.2:8080/alfresco/s</endpoint-url>
           <identity>user</identity>
        </endpoint>
      </remote>
    </config>
```

**Comment by douglascrp** [comment]
Cool... just like we do with share on separate server.
I'm going to test it.

Thank you.

**Comment by draperd** [comment]
You're welcome... the client that the Maven archetype creates can be thought of as an "empty" version of Share. It's built on Surf, so everything you no about Surf will apply, e.g it will support configuration models (but you'll need to make your pages reference that configuration).

**Comment by douglascrp** [comment]
Awesome
