### ISSUE TITLE
Current Aikau version breaks search after scrolling

### ISSUE THREAD

**Issue by gehriga** [Alfresco/Aikau#1131]
It seems like one of the recent Aikau versions introduced a bug on the search page related to infinite scroll. 

My setup: Alfresco 5.1.0.5, Aikau 1.0.74

Steps to reproduce: 

1. Search for a term bringing some results, e.g. '*' 
2. On the search page, scroll down a bit to select a filter, e.g. 'modified' that would return only a few results (< 25) 

Expected result: you should see the number of results indicated by the filter you've just selected 
Actual result: no results can be found 

If you do not scroll before selecting a filter in step 2, the correct number of results is shown. 
Inspecting the network request in the browser's developer tools you can see that without scrolling results starting at index 0 are requested. After scrolling results starting at index 25 are requested. 

So obviously the infinite scroll feature is misbehaving and trying to show 'page 2' after scrolling. 

The bug isn't there if you use Aikau 1.0.39.8 which was originally delivered with Alfresco 5.1.0.5 

Kind regards, 
Andreas Gehrig

**Comment by draperd** [comment]
OK, thanks for raising this issue - I'll investigate and report back.

**Comment by draperd** [comment]
Accidental close - apologies, re-opened again!

**Comment by draperd** [comment]
I've been able to reproduce this issue - thanks for reporting it, as yet I haven't determined what has caused the issue or when it was introduced. I'll continue to investigate.

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/AKU-1007 to address this and we'll get a fix out (along with various hotfix releases as soon as possible)

**Comment by gehriga** [comment]
I appreciate this, thanks!

**Comment by draperd** [comment]
OK... I have a fix, just writing the unit tests to prevent regressions. This fix will go into 1.0.75 and will be back ported to 1.0.67.1 and 1.0.72.3 hot-fix releases (the hot-fix releases should be made later today, 1.0.75 will be released later this week or early next week).

**Comment by draperd** [comment]
The 1.0.72.3 hot fix release is now available, we're having some issues getting the 1.0.67.1 release out.

**Comment by gehriga** [comment]
Do you know if one of these hotfix releases will go into Alfresco 5.1.1 or an subsequent release?

**Comment by draperd** [comment]
I'm not sure what is going to happen with 5.1.1 - I'm going to chase that up now, it's not actually my call. I'll update this issue when I know. The 1.0.67.1 is now available though.

**Comment by draperd** [comment]
Forgot to close this - the fix is available in 1.0.75 as well as the previously mentioned hot-fix releases.
