### ISSUE TITLE
Option needed to exclude "additionalButton" from being updated with current form data

### ISSUE THREAD

**Issue by AFaust** [Alfresco/Aikau#1171]
In one project I was recently working on we included a "reset" type button into an alfresco/forms/Form instance that contained a pre-defined set of values for each form field and published to the "setValueTopic" of the form. Unfortunately the form module always overrides the configured payload of any button in the "widgetsAdditionalButtons" property without providing any option to disable the override in general / per-button. Such an option is necessary.
In that project we ended up using a workaround based on a custom button module that just copied the configured payload and overrides any potentially externally manipulated payload as part of the onClick function call.

**Comment by draperd** [comment]
Thanks for raising this... I'll raise a feature request to address it and get to it when I can

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/AKU-1044 to address this. I'll try to get to it as soon as I can.

**Comment by draperd** [comment]
This has been handled in #1196 and will be available in the 1.0.81 release. I'll close this issue when it's available.

**Comment by draperd** [comment]
Closing as 1.0.81 is now available.
