### ISSUE TITLE
Documentation about src/test/resources/config/Suites.js needs update

### ISSUE THREAD

**Issue by AFaust** [Alfresco/Aikau#1184]
The documentation about changes to be made to src/test/resources/config/Suites.js when running tests in https://github.com/Alfresco/Aikau/wiki/Aikau%20Setup%20(Windows) or https://github.com/Alfresco/Aikau/wiki/Aikau%20Setup%20(Linux) is no longer reflecting the actual contents of the file. Instead of xbaseFunctionalSuites and baseFunctionalSuites there are now allTests and someTests.

**Comment by draperd** [comment]
Thanks for raising this... I'll make sure it gets corrected.

**Comment by draperd** [comment]
This has now been updated.
