### ISSUE TITLE
CoreXhr not depending on Core

### ISSUE THREAD

**Issue by HansDeBal** [Alfresco/Aikau#1254]
Hi,

Just a remark/question: I see alfresco/core/CoreXhr does not require alfresco/core/Core (not in the define-parameters of CoreXhr). But since CoreXhr is using methods of Core (eg alfCleanFrameworkAttributes), shouldn't CoreXhr explicitly define a dependency on Core?

Thanks

**Comment by draperd** [comment]
Yes, you're quite right... the reason why we've gotten away with this is because in almost all cases where a widget mixes in CoreXhr it is also mixing in Core. I'll get this changed. Thanks for raising this.

**Comment by draperd** [comment]
I've created a pull request to address this - could you let me know if you're happy with the changes please?
