### ISSUE TITLE
Loading message in Tutorial 1  not correct anymore

### ISSUE THREAD

**Issue by jgoldhammer** [Alfresco/Aikau#1263]
In Step 3, the loading message is not seen anymore - It shows nothing for me...
https://github.com/Alfresco/Aikau/blob/develop/tutorial/chapters/Tutorial1.md#step-3-show-the-user-files

**Comment by jgoldhammer** [comment]
Sorry, it pops up and disappears very quickly...

**Comment by draperd** [comment]
Ah, yes... we changed the way loading is done a while ago - those screenshots in the tutorial are out of date, but conceptually the behaviour is more or less the same.
