### ISSUE TITLE
Edit form (FormRuntimeService) and mandatory files assocs

### ISSUE THREAD

**Issue by aviriel** [Alfresco/Aikau#1270]
If in the content type there is a mandatory assoc, then on the edit form you cannot click "save/ok" without changing the assoc.
Way to reproduce:
1. Create a custom type (can be a datalist) with a mandatory association
2. Create new item and fill the create form, add assoc.
3. Click "Edit"
4. The form is opened

Result: "OK" button will be disabled before you detach a file and attach it again.
Expected result: assoc already exist, you don't need to do anything.

**Comment by draperd** [comment]
Thanks for raising this... just to clarify, is this reproducible in the Data Lists pages I blogged about - I just want to make sure I have all the information to quickly debug and fix the issue.

**Comment by aviriel** [comment]
Yes, it's reproducible on https://github.com/draperd/Alfresco-Share-Extensions/tree/master/aikau-datalists, but default datalist types does not include any mandatory associations with cm:content, so no way to reproduce it without creating new datalist type.

**Comment by draperd** [comment]
OK, cool... I'll take a look at this as soon as I can - thanks again for the feedback!

**Comment by draperd** [comment]
Created https://issues.alfresco.com/jira/browse/AKU-1112 to look into this

**Comment by draperd** [comment]
The fix for this will be in the 1.0.96 release.
