### ISSUE TITLE
aikau-sandpit: blank page on 2/3 Android devices.

### ISSUE THREAD

**Issue by deas** [Alfresco/Aikau#1289]
Two (version 5 and 7) of three android devices presented me a blank aikau-sandpit home page. Turned out, it is caused by line 18 in the document

```
locale: (navigator.languages
(navigator.languages ? navigator.languages[0] : (navigator.language || navigator.userLanguage)).toLowerCase(),
```

when `navigator.languages` is an empty array.

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/AKU-1126 to address this issue, however having looked into it, it seems that the problematic code is actually in Surf and therefore cannot be addressed in the Aikau code base. Therefore I will re-assign the JIRA ticket to the appropriate location - unfortunately this does mean that it is unlikely to be resolved as quickly as it would have been if the code problem existed in Aikau. There are workarounds to the problem (such as creating an extension module to inject code before the Dojo bootstrap line) however this isn't going to be a priority for the Sandpit. However, we should address this issue within Surf to support Android browsers running Share.

It would still be useful to know exactly which Android devices, OS versions and browsers were used as it is not a problem across all Android devices (it works on my Android devices for example) and this information will assist with reproducing and verifying the problem.

**Comment by draperd** [comment]
JIRA issue moved to https://issues.alfresco.com/jira/browse/SHA-1931
