### ISSUE TITLE
MultiSelectInput Issue

### ISSUE THREAD

**Issue by AlexRFS** [Alfresco/Aikau#1300]
Hello, 
I have the MultiSelectInput with following defenition:
```JAVASCRIPT
{
		   name: "alfresco/forms/controls/MultiSelectInput",
		   config: {
                     id:"Approvers",
		      label: "Approvers",
		      name: "assoc_dfildf_Approvers_added",
		      width: "200px",
		      choiceCanWrap: true, // Whether chosen items' text can wrap over multiple lines (defaults to true)
		      choiceMaxWidth: "100%", // The maximum width of chosen items (defaults to 100%)
		      optionsConfig: {
		         labelAttribute: "label",  // What's displayed in the dropdown and choice (defaults to label)
		         queryAttribute: "label",  // The attribute that's used when filtering the dropdown (defaults to name)
		         valueAttribute: "value", // The actual submitted value for each chosen item (defaults to value)
		         publishTopic: "ALF_GET_FORM_CONTROL_OPTIONS",
		         generatePubSubScope:true,
		         publishPayload: {
		        	 resultsProperty : "options",
	                    url: url.context + "/proxy/alfresco/api/forms/picker/authority/children?selectableType=cm:person&size=1000&groupFilter=DFL_APPROVERS",
	                    itemsAttribute : "data.items",
	                    labelAttribute : "name",
	                    valueAttribute : "nodeRef"
		         }
		      }
		   }
};
```
And i have added this control to the form,but when form is submitted there is no selected value in the posted data..And i can't find the input with my name assoc_dfildf_Approvers_added in html markup

Version of aikau: 1.0.85

**Comment by draperd** [comment]
So just to to clarify...

The form submission payload contains the "assoc_dfildf_Approvers_added" property (the configured "name" attribute) but it is not assigned the value or values that have been selected from available options?

I wouldn't expect to see "assoc_dfildf_Approvers_added" anywhere in the HTML - however, you should see "Approvers" as the ID of the element.

It looks like you've based your configuration on an example from our unit test pages and there are tests for this widget. It might be possible that we've missed something, but it does appear to be functioning correctly on the test page and in the tests.

It's possible I'm either missing some subtlety in your question.

**Comment by AlexRFS** [comment]
The form submission payload doesn't contains  the "assoc_dfildf_Approvers_added" property

**Comment by draperd** [comment]
I'm worried that we're talking at cross purposes here... I'm testing it out locally, and I can see that it is working as I'd expect.

I'm assuming that you've got the MultiSelectInput in a form? Have you got the alfresco/logging/DebugLog on your page (running in debug mode) so that you can see the publications.

I'd definitely recommend getting the unit test app running and comparing the results in the test page.

**Comment by AlexRFS** [comment]
Dave
I'm tested on different page with following configuration:
The form and inside is MultiSelectInput, and it works correctly.
But in my configuration i have this form inside of VerticalWidgets, which is inside of ControlRow,And this ControlRow inside of ClassicWIndow...And it's not working...

**Comment by draperd** [comment]
OK, can you paste in your entire model so I can reproduce the problem locally please? It does sound like a rather unusual hierarchy though.... ClassicWindow -> ControlRow -> VerticalWidgets -> Form -> MultiInputSelect.

A ControlRow is **only** supposed to be used within a Form, there should be no need for the VerticalWidgets either... perhaps we can take a step back so I can understand why you're trying to use that structure... what form layout are you trying to achieve?

**Comment by AlexRFS** [comment]
Dave, I will send my current structure on Monday. 

--
С уважением,
Александр Гирин

**Comment by AlexRFS** [comment]
Hi Dave.
It was a problem with verticalWidgets, i removed all verticalWidgets and Multiselect input now work like a charm.

**Comment by draperd** [comment]
OK, great... I'm glad you resolved the problem.
