### ISSUE TITLE
Problem on documents loading with alfresco/forms/controls/DocumentPicker

### ISSUE THREAD

**Issue by andrakula** [Alfresco/Aikau#1302]
the DocumentPicker brings to the crash my browser. If I choose a folder on the left site, then the subfolders are loaded and a lot of requests are sent. And it ends never.

`{name: "alfresco/forms/Form",
        config: {
           okButtonPublishTopic: "MY_FORM",
           widgets: [
              {
                 name: "alfresco/forms/controls/DocumentPicker",
                 config: {
                    label: "Choose a document",
                    name: "document"
                 }
              }]}}`

This request is sent a lot if time on load:
/alfresco/s/slingshot/doclib2/doclist/all/node/workspace/SpacesStore/**{chosen-site}**?filter=path&sortField=cm%3aname&sortAsc=true&view=browse&size=10&noCache=**{only this parameter is changed}**&pos=1&libraryRoot=workspace%3a%2f%2fSpacesStore%2f**{chosen-site}**&alf_ticket=TICKET_cbfbf43c4cc372f74f43717c4ec85722e325fc88
![screenshot](https://cloud.githubusercontent.com/assets/7724548/20482965/e3b2f92e-afef-11e6-8407-e24fc51f4af5.png)

**Comment by draperd** [comment]
Thanks for raising this issue. Could you please let me know what versions of Alfresco and Aikau that you're using please?

Does this problem occur within Share (as it is out-of-the-box) or in a customization or is it even occurring in a custom client? Does this problem only occur on one browser type (i.e. Chrome, Firefox) or does it occur on all browsers? 

It sounds like there is some kind of circular behaviour going on, perhaps it is looped publications/subscriptions? 

Is there any custom code involved or are you just using out-of-the-box Aikau widgets and services? Some additional information will help resolve this problem.

If you're able to provide the JSON model that builds the page (or relevant section of the page) it will be very useful.

**Comment by andrakula** [comment]
Hi Dave,

I try it with latest Aikau version (1.0.96) and Alfresco repository version 5.0.3 and 5.1.1.
This problem occur with my customization of share. I added a new webscript with a simple form and DocumentPicker.

I could localized the problem: 
This problem occurs if I add to my webscript  
`<import resource="classpath:/alfresco/site-webscripts/org/alfresco/share/imports/share-header.lib.js">` and call getHeaderServices(). 
The "bad guy" is `alfresco/services/DialogService`.

The short way, to reproduce this problem is only to add DialogService to the jsonModel:

```
model.jsonModel = {
services: [
  "alfresco/dialogs/AlfDialogService",
  "alfresco/services/DocumentService",
  "alfresco/services/SiteService",
  "alfresco/services/DialogService"
],
widgets: [
		{
		name: "alfresco/forms/Form",
        config: {
           okButtonPublishTopic: "FORM_CONTENTS",
           widgets: [
              {
                 name: "alfresco/forms/controls/DocumentPicker",
                 config: {
                    label: "Choose a document",
                    name: "document"
                 }
              }
           ]
        }
     }
]};
```

**Comment by draperd** [comment]
OK... so why have you got 2 different dialog services? The AlfDialogService is deprecated (see the JSDoc: https://dev.alfresco.com/resource/docs/aikau-jsdoc/AlfDialogService.html).

I don't think that this issue can be fixed within the Aikau code base... the solution is simply to remove the AlfDialogService from the page model and just use the DialogService.

**Comment by andrakula** [comment]
the import of AlfDialogService was in the example I used. 
Thank you for help!

**Comment by draperd** [comment]
No problem. The deprecated service definitely doesn't make it obvious I know. If you can point me at the example that you followed then I'll see if I can change it.

I'm glad you were able to get the issue resolved. Please let me know if you have any other issues that you need help with.
