### ISSUE TITLE
Cannot set the target folder for targetUpload widget

### ISSUE THREAD

**Issue by AlexRFS** [Alfresco/Aikau#1306]
Hello
Sorry for my question in issues..
Could you tell me, is it possible to set target folder for the 'targetUpload' widget?I  can't find how to do it..

**Comment by draperd** [comment]
No problem, it would probably be better for you to raise them in the Alfresco Community int he future (https://community.alfresco.com/community/ecm)

If you mean the UploadTarget (https://dev.alfresco.com/resource/docs/aikau-jsdoc/UploadTarget.html) widget, then no. This is provided in order for the user to select different targets.

However, if you look at the source you'll see that the majority of the work is done by the "alfresco/documentlibrary/_AlfDndDocumentUploadMixin" and "alfresco/node/NodeDropTargetMixin" modules that are mixed into that widget. It should be relatively straightforward to build your own custom widget re-using these modules.

I'm going to close this issue as there is nothing for me to fix.
