### ISSUE TITLE
DojoSelect value is empty when form submit

### ISSUE THREAD

**Issue by AlexRFS** [Alfresco/Aikau#1307]
Hello,
I have a form defined like this:
```JAVASCRIPT
var RequestSubjectMatter = {
	      name: "alfresco/forms/controls/DojoValidationTextBox",
	      widthPx: "200",
	      config: {
	  	      label: "Subject-matter",
	  	      name: "prop_dfildf_SubjectMatter",
	  	      value:"TEST SUBJ",
	  	      requirementConfig: {
	    	    initialValue: true
	    	  }  
	      }      
};
var Comment = {
	      name: "alfresco/forms/controls/TextArea",
	      widthPx: "400",
	      config: {
	  	      label: "Comment",
	  	      value:"TEST COMMENT",
	  	      name: "prop_dfildf_Comment"
	      }      
};
var RequestPriority = {
	      name: "alfresco/forms/controls/DojoSelect",	
	      widthPx:"200",
	      config: {
	      label: "Priority",
	      name: "assoc_dfildf_priorityRef_added",
	      width:"200",
	      forceWidth:true,
	      truncate:true,
	      value:"workspace://SpacesStore/50d37781-0fb2-4b37-959b-7d4f276ada52",
	      generatePubSubScope:true,
	      optionsConfig: {
	        publishTopic: "ALF_GET_FORM_CONTROL_OPTIONS",	
	        generatePubSubScope:true,
	        publishPayload: {
	          url: url.context + "/proxy/alfresco/dfi/GetListData?siteName=legal&listName=Priorities&columnsReturn=dfildf:Priority", //&listName=Priorities&columnsReturn=dfildf:Priority"
	          itemsAttribute: "items",
	          labelAttribute: "dfildf:Priority",
	          valueAttribute: "nodeRef"
	        }
	      }
	    }
};
var RequestLocation = {
	      name: "alfresco/forms/controls/DojoSelect",	
	      widthPx:"200",
	      config: {
	      label: "Location",
	      width:"200",
	      forceWidth:true,
	      truncate:true,
	      generatePubSubScope:true,
	      name: "assoc_dfildf_locationRef_added",
	      value:"workspace://SpacesStore/76d18e51-dc66-4c23-9c3f-2eca16c42834",
	      optionsConfig: {
	    	generatePubSubScope:true,	      
	        publishTopic: "ALF_GET_FORM_CONTROL_OPTIONS",	        
	        publishPayload: {
	          url: url.context + "/proxy/alfresco/dfi/GetListData?siteName=legal&listName=Locations&columnsReturn=dfildf:Location", //&listName=Locations&columnsReturn=dfildf:Location"
	          itemsAttribute: "items",
	          labelAttribute: "dfildf:Location",
	          valueAttribute: "nodeRef"
	        }
	      }
	    }
}; 
var vipApprovers = {
		   name: "alfresco/forms/controls/MultiSelectInput",
		   config: {
		      label: "Vip Approvers",
		      name: "assoc_dfildf_vipApprovers_added",
		      valueDelimiter:",",
		      width: "200px",
		      choiceCanWrap: true, // Whether chosen items' text can wrap over multiple lines (defaults to true)
		      choiceMaxWidth: "100%", // The maximum width of chosen items (defaults to 100%)
		      value:"workspace://SpacesStore/ee7e860f-5054-4545-8381-cb8648c2ee05",
		      optionsConfig: {
		         labelAttribute: "label",  // What's displayed in the dropdown and choice (defaults to label)
		         queryAttribute: "label",  // The attribute that's used when filtering the dropdown (defaults to name)
		         valueAttribute: "value", // The actual submitted value for each chosen item (defaults to value)
		         publishTopic: "ALF_GET_FORM_CONTROL_OPTIONS",
		         generatePubSubScope:true,
		         publishPayload: {
		        	 resultsProperty : "options",
	                    url: url.context + "/proxy/alfresco/api/forms/picker/authority/children?selectableType=cm:person&size=1000&groupFilter=DFL_VIP_APPROVERS",
	                    itemsAttribute : "data.items",
	                    labelAttribute : "name",
	                    valueAttribute : "nodeRef"
		         }
		      }
		   }
};
var Approvers = {
		   name: "alfresco/forms/controls/MultiSelectInput",
		   config: {
		      label: "Approvers",
		      name: "assoc_dfildf_vipApprovers_added",
		      valueDelimiter:",",
		      width: "200px",
		      choiceCanWrap: true, 
		      choiceMaxWidth: "100%", 
		      value: "workspace://SpacesStore/ee7e860f-5054-4545-8381-cb8648c2ee05",
		      optionsConfig: {
		         labelAttribute: "label",  
		         queryAttribute: "label",  
		         valueAttribute: "value", 
		         publishTopic: "ALF_GET_FORM_CONTROL_OPTIONS",
		         generatePubSubScope:true,
		         publishPayload: {
		        	 resultsProperty : "options",
	                    url: url.context + "/proxy/alfresco/api/forms/picker/authority/children?selectableType=cm:person&size=1000&groupFilter=DFL_VIP_APPROVERS",
	                    itemsAttribute : "data.items",
	                    labelAttribute : "name",
	                    valueAttribute : "nodeRef"
		         }
		      }
		   }
};
var nodeId = "workspace://SpacesStore/8bda41a8-29d5-4e4d-bbac-48d4551c84e5";
var form =	{   
    		name: "alfresco/forms/Form",
    		config: {
		    	showOkButton: true,
		    	okButtonLabel: "Save request",   
		    	showCancelButton: true,
		    	cancelButtonLabel: "Cancel",		    		   
		    	okButtonPublishTopic: "ALF_CRUD_CREATE",
		    	okButtonPublishGlobal: true,   
		    	okButtonPublishPayload: {
		    		    	  url: nodeId ? "api/node/workspace/"+ nodeId.replace('workspace://','') + "/formprocessor":"api/type/dfildf%3ALegalRequests/formprocessor",
		    		    	  failureMessage:"Success",
		    		    	  successMessage:"Failed",
		    		    	  alf_redirect:"/share"
		    		      	},
		        widgets: [RequestPriority,RequestLocation,RequestSubjectMatter,Comment,vipApprovers,Approvers]
    			  }
};
model.jsonModel = { widgets:  [form] ,   services: ["alfresco/services/CrudService",
	"alfresco/services/OptionsService",
	"alfresco/services/FileUploadService",
    "alfresco/services/ContentService",
    "alfresco/services/DialogService",
    "alfresco/services/DocumentService",
    "alfresco/services/SiteService",
    "alfresco/services/NotificationService"] };
```

CASE 1:
If i submit this form,without any changes, it will send to the service only values of MultiSelectInputs, another fields which was set via DoJo Select will sent as empty strings.
CASE 2:
i changed some textbox field all fields will  sent to the service. 
CASE 3:
i changed some DoJoSelect value, case 1 will repeat

Aikau version:1.0.85

**Comment by draperd** [comment]
OK... just to clarify, if you've not selected a value in the Select fields (btw DojoSelect and DojoValidationTextBox are deprecated, you want to use Select and TextBox instead) then their values are sent as empty strings - presumably it appears in the Select box that something has been selected?

Are you then saying that if you enter text that **all** fields are submitted correctly, but if you select something from the Select menu then they're submitted as empty strings?

Is it possible that your API for returning options is not working correctly? Can you provide an example response body of what they return?

**Comment by AlexRFS** [comment]
Dave,
**Case 1:**
I open my page and click Save request:
![image](https://cloud.githubusercontent.com/assets/12934988/20603424/8bf413be-b272-11e6-8453-9be7a160662d.png)
As you can see the fields assoc_dfildf_locationRef_added,and assoc_dfildf_priorityRef_added sent as empty strings.
**There is a capture of what returns my api:**
![image](https://cloud.githubusercontent.com/assets/12934988/20603496/cbe57800-b272-11e6-8ac0-13f99d65d3f1.png)
**CASE 2:** I open my page and change Subject-matter textbox value and click Save request, there is the result:
![image](https://cloud.githubusercontent.com/assets/12934988/20603544/0d1337b8-b273-11e6-81c8-587c572a5ff7.png)
As you can see now all fields were sent to the service.

**Comment by draperd** [comment]
OK.... why do you have generatePubSubScope set to true on each of the Select form controls?

This is almost certainly going to mean that they won't be able to communicate with the outer form, this probably explains why the values are missing. 

Can you try removing those lines of configuration please?

**Comment by AlexRFS** [comment]
Ou,thanks, noticed that.
Now it works fine,
And one more question Dave, why the arrow of the Select control have a margin from right side?

**Comment by draperd** [comment]
I don't actually know why the arrows have moved... in general the styling looks wrong in your screenshots, have you got any custom CSS overlays that might be impacting the Aikau controls? Are there any error messages in the Share server output or the browser console?

**Comment by AlexRFS** [comment]
Dave i don't have any custom CSS..and i don't see any errors in console or Share server  output

**Comment by AlexRFS** [comment]
I see it only when selected value i short, i i select the value wich have more charecters the arrow is move to the end of control

**Comment by draperd** [comment]
Ah, it's probably because you're setting a width attribute on them. Try removing that.

**Comment by AlexRFS** [comment]
Yes, when i remove width config all good,
But i need the fixed dropdown, to be the same width as other controls like a textbox.

**Comment by draperd** [comment]
I've I just set ```width: "200px",``` without the forceWidth or truncate or widthPx it appears fine for me.

**Comment by AlexRFS** [comment]
Will check tomorrow 

--
С уважением,
Александр Гирин

**Comment by AlexRFS** [comment]
Dave, yes, i have width:"200" instead of  width:"200px"..Now it's ok.
And one more question, please..In my datalist i have association field - dfildf:locationRef 
On my custom page i want to create new items and edit existiing items.
I have added Select control with name:
assoc_dfildf_locationRef_added
When i save the form, new item will added to this field, but how to be in case when i want to edit this item? Form will send assoc_dfildf_locationRef_added and it will add new value to this field, but store previous.

**Comment by draperd** [comment]
If you're working with Data Lists in an Aikau context then I'd suggest you have a read of this blog post (https://community.alfresco.com/community/ecm/blog/2016/09/14/aikau-1085-data-lists) and the various linked posts. 

The Data List implementation in Share goes through the XML-based forms runtime and Aikau is now providing a service for accessing this data. Using this might be the quickest way to solving your problems - certainly in regards to handling the both create and edit scenarios.

Ultimately though when editing you just need to load the data from an existing GET REST API or create a custom one and then pass the data into your Aikau form and then call a PUT API to update the item that you retrieved.

**Comment by AlexRFS** [comment]
Dave i able to load the data from an existing GET REST API and then pass the data into your Aikau form, but when i need to save it form of existing item, i want to know, what i should pass to form processor, to replace existing association value with new from the my form.Now it sends with assoc_MYFIELD _added prefix and allows only add new values to this field but now replace it.

**Comment by draperd** [comment]
Unfortunately I can't help you there (and this isn't actually related to Aikau, it's more to do with Data Lists)... I'd suggest you try it out in the standard Data Lists page in Share with browser debugger tools running and inspect the XHR requests that are made when you perform a save operation. You should be able to map these into your configuration.
