### ISSUE TITLE
SiteService should not load edit-site.js or at least check if it's already been loaded

### ISSUE THREAD

**Issue by AFaust** [Alfresco/Aikau#1331]
For some reason I cannot understand, the SiteService module is loading the edit-site.js file for the legacy YUI dialog and Share is no longer loading this file itself (as has always been the case before). This is in sharp contrast to the legacy YUI create-site.js which is still loaded by Share's resources.get.html.ftl and not by SiteService. Furthermore, SiteService does not check if edit-site.js has already been loaded (e.g. by checking Alfresco.module.getEditSiteInstance as is already done for the create site dialog.

Since removing the (from my point of view) "illegal" active load of edit-site.js from the SiteService and re-including it in resources.get.html.ftl would break backwards compatibility with Alfresco releases that do not load that JS file, the SiteService should at least check if the module has already been loaded and not actively load it itself in that case.
This is necessary to allow modules that might need/want to customize the legacy edit site dialog to load their extension JS after edit-site.js has been included using a customization via a Surf extension module. The way it currently is - even if edit-site.js were loaded in resources.get.html.ftl - there will be a chance the edit-site.js file is re-loaded asynchronously, re-initializes the YUI "class" and thus undoes any extension already applied to it.

**Comment by draperd** [comment]
Yes, I don't disagree with any of that. It has been like that for a very long time (not that this is any excuse) - but I will rectify this.

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/AKU-1150 to address this and will try to complete it within the current sprint.

**Comment by draperd** [comment]
Fix now available in 1.0.100
