### ISSUE TITLE
es6-promise.map cannot be found

### ISSUE THREAD

**Issue by AFaust** [Alfresco/Aikau#1350]
I have included Aikau 1.0.101 in a customer project and on a page that uses an AlfFilteredList the browser console (Edge) and network monitor will list an 404 error for the es6-promise sourceMap every time the list is reloaded. That file is not yet included in the js/lib/es6-promise folder and should probably be added (assuming that it should be common policy to include those *.map files, similar to how showdown.js.map is already included).

**Comment by draperd** [comment]
OK, thanks for the update... I'll add the .map.js file... I hadn't realised it's omission would cause any problems.
