### ISSUE TITLE
External JS dependencies loaded in Alfresco Enterprise 5.1.2

### ISSUE THREAD

**Issue by plus-** [Alfresco/Aikau#1374]
It seems that in Enterprise 5.1.2, our customization in Share loads outside scripts. The problem is after investigating, those scripts are not defined in our customization code but in the Aikau jar, our testers report that without our customization amp they don't have the following scripts accessed.

This is the problematic template in Aikau that loads the scripts in question:

https://github.com/Alfresco/Aikau/blob/develop/aikau/src/main/resources/extension-webscripts/dojo-bootstrap.get.html.ftl

Could you tell me what in our customization could possibly trigger the presence of those scripts tag in Share?

PS: we do have defined some custom `<dojo-pages><packages>` in our share config

**Comment by plus-** [comment]
This is a huge problem for internal network as it slows down the application page loading.

**Comment by draperd** [comment]
Without access to your customization code it would be impossible to tell. What exactly are you customizing (i.e. what part of Share, what dependencies are you pulling in, is this an Aikau extension, etc?)

**Comment by draperd** [comment]
Actually that extension WebScript looks like an experimental Angular feature - it shouldn't be deployed by default... check your module deployment to ensure it's not accidentally been deployed. It's definitely deployed by default out-of-the-box

**Comment by draperd** [comment]
See this blog post for more details on that extension: https://community.alfresco.com/community/ecm/blog/2016/05/03/aikau-1066-angular-2-integration

**Comment by plus-** [comment]
Thanks for the quick reply, we did set `<module-deployment><mode>auto</mode>` in our share config, so I suppose this is our fault as we should have used the module's configuration
