### ISSUE TITLE
modify Aikau.jar inside my amp

### ISSUE THREAD

**Issue by RedRaccoon** [Alfresco/Aikau#1375]
Hello

In my job I did some change inside the aikau.jar 

https://www.noelshack.com/2017-17-1493214705-aikau.jpg 

I added some custom actions (especially in preview/PdfJs/documentPreview.js and around)

everything is working fine, I deploy my custom aikau.jar as they explained (inside tomcat/webApps/share/web-inf/lib ) 

But today I had an idea, as I have to change differents version of aikau.jar I was wondering if with the customize style of Alfresco (1 extension file, 1 get.js widget = custom, 1 custom.js) I could just **add my changes inside my amp** ?

I tried to do this today but without sucess 

In my opinion it must be possible as the file are on the webApp but I have the feeling that .jar are not customizable as they are already encapsuled 

Thank you in advance

**Comment by draperd** [comment]
You should never be changing the contents of the Aikau JAR. What are you trying to achieve? If you're trying to "monkey patch" the existing code then this is going to be unsupported. 

Rather than patching the code you should look to try and extend the existing modules and override functions or provide reconfiguration.

**Comment by RedRaccoon** [comment]
Well, I wan't to override and create function of *.js of the aikau ( like PdfJs.js or DocumentView.js )

I know how to extend/override in Alfresco ( for components )
But I don't know how to extend/override Aikau's *.js because he is inside a .jar

**Comment by draperd** [comment]
Why not create your own modules that extend the modules in the Aikau JAR and then override the functions that you want to? You would then you reference your own modules in your page definition. 

This is the recommended approach as it provides a future proof way of making customization (your own modules in your own JAR will work against future versions of the Aikau JAR)

**Comment by RedRaccoon** [comment]
thank you for your response I'll do that
