### ISSUE TITLE
Customizing a widget from 2 different modules not working

### ISSUE THREAD

**Issue by plus-** [Alfresco/Aikau#1379]
More specifically the search result widget (https://dev.alfresco.com/resource/docs/aikau-jsdoc/AlfSearchResult.html)

I have the following code in 2 different modules:

in module 1:
```
var searchResultPage = widgetUtils.findObject(model.jsonModel.widgets, "id", "FCTSRCH_SEARCH_RESULT");

if(searchResultPage && searchResultPage.config) {
  searchResultPage.config.mergeActions = true;
  searchResultPage.config.additionalDocumentAndFolderActions = ["action1"];
}
```

and in module 2:
```
var searchResultPage = widgetUtils.findObject(model.jsonModel.widgets, "id", "FCTSRCH_SEARCH_RESULT");

if(searchResultPage && searchResultPage.config) {
  searchResultPage.config.mergeActions = true;
  searchResultPage.config.additionalDocumentAndFolderActions = ["action2"];
}
```

I will only ever see action1 as an additional action in the search result page. If I comment out the code from module 1 then action2 will be visible, which leads me to think they are mutually exclusive.

**Comment by SanjayBandhniya** [comment]
Hi,
I have implemented above code but I am not able to see custom action.
can you help me to resolve issue?
![Untitled](https://user-images.githubusercontent.com/10328297/77036830-0077f200-69d6-11ea-9bb8-a85b8d0af0f9.png)
