### ISSUE TITLE
Aikau 1.0.102 release

### ISSUE THREAD

**Issue by marsv024** [Alfresco/Aikau#1385]
Is there any plan on when 1.0.102 is going to be released? Currently there are quite a few commits on develop that are not in 1.0.101.11 that would be good to have.

**Comment by davidcognite** [comment]
There's not currently a plan, but I can't see any reason not to release it if there are commits that would be useful on it. I'll make sure all the changes on the 1.0.101 HF branch are merged, run the tests and release if they're green.

**Comment by marsv024** [comment]
Much appreciated @davidcognite !

**Comment by davidcognite** [comment]
1.0.102 released. Enjoy!

**Comment by marsv024** [comment]
@davidcognite Thanks!
