### ISSUE TITLE
/archetype-catalog.xml' is not supported anymore

### ISSUE THREAD

**Issue by Oleg25** [Alfresco/Aikau#1392]
![image](https://user-images.githubusercontent.com/2542786/33991409-8e3fcc66-e0df-11e7-84b3-4f3cf9d7fea8.png)
I try to do first step in  Aiku/Tutorial

mvn archetype:generate -DarchetypeCatalog=https://artifacts.alfresco.com/nexus/content/groups/public/archetype-catalog.xml -DarchetypeGroupId=org.alfresco -DarchetypeArtifactId=aikau-sample-archetype -DarchetypeVersion=RELEASE

**Comment by ivanovpavel1983** [comment]
Oleg, hello. It's easy...
In maven settings.xml add profile:
<profile>
      <id>Alfresco</id>
      <repositories>
        <repository>
          <id>archetype</id>
          <url>https://artifacts.alfresco.com/nexus/content/groups/public</url>
          <releases>
            <enabled>true</enabled>
            <checksumPolicy>fail</checksumPolicy>
          </releases>
          <snapshots>
            <enabled>true</enabled>
            <checksumPolicy>warn</checksumPolicy>
          </snapshots>
        </repository>
      </repositories>
    </profile>

and run command:

mvn archetype:generate -Dmaven.wagon.provider.http=httpclient -DarchetypeGroupId=org.alfresco -DarchetypeArtifactId=aikau-sample-archetype -DarchetypeVersion=1.0.103

**Comment by shiv16676** [comment]
> Oleg, hello. It's easy... In maven settings.xml add profile:
> 
> `<profile> <id>Alfresco</id> <repositories> <repository> <id>archetype</id> <url>https://artifacts.alfresco.com/nexus/content/groups/public</url> <releases> <enabled>true</enabled> <checksumPolicy>fail</checksumPolicy> </releases> <snapshots> <enabled>true</enabled> <checksumPolicy>warn</checksumPolicy> </snapshots> </repository> </repositories> </profile> `
> 
> and run command:
> 
> mvn archetype:generate -Dmaven.wagon.provider.http=httpclient -DarchetypeGroupId=org.alfresco -DarchetypeArtifactId=aikau-sample-archetype -DarchetypeVersion=1.0.103

It doesn't work for me.....
tried with different version which exists in maven central repo but no luck

> mvn archetype:generate -Dmaven.wagon.provider.http=httpclient -DarchetypeGroupId=org.alfresco -DarchetypeArtifactId=aikau-sample-archetype -DarchetypeVersion=1.0.101.19
