### ISSUE TITLE
Tutorial 7 - GRAVE: Could not find compressed file: /tutorial/UserAndGroupService.js

### ISSUE THREAD

**Issue by angelborroy** [Alfresco/Aikau#187]
Following steps from Tutorial 7, this exception is thrown on accessing http://localhost:8090/aikau-sample/page/ap/ws/users-and-groups

**Comment by draperd** [comment]
I'm assuming you've actually created that service (it's part of the tutorial steps)? Have you followed the "What to do if things go wrong" steps: https://github.com/Alfresco/Aikau/blob/master/tutorial/chapters/About.md

I just want to understand if there is an error in the tutorial itself, or if you might have missed something along the way.

**Comment by angelborroy** [comment]
I've been following the steps point by point till the end of Chapter 7.
Creating the service is not part of the tutorial, so I have no "tutorial/UserAndGroupService" created.

**Comment by angelborroy** [comment]
Sorry, I've misunderstood you. I thought you were talking about "api/rootgroups/" repo service and it's available at repo side, so no creation is required. 

I'm trying to move UserAndGroupService.js service to another location in the project. It seems current path it's not (webapp/js/tutorial) is not been loaded.

**Comment by angelborroy** [comment]
I've moved the service to "aikau-client/src/main/webapp/js/aikau/1.0.14/alfresco/service/UserAndGroupService.js" and it's working now. 

(Obviously I've had to change also "tutorial/UserAndGroupService" to "alfresco/services/UserAndGroupService" in users-and-groups.get.js)

**Comment by draperd** [comment]
The instructions for creating the service are located here in Tutorial 7: https://github.com/Alfresco/Aikau/blob/master/tutorial/chapters/Tutorial7.md#step-4-create-a-service

You must have accidentally missed that step.

**Comment by draperd** [comment]
Also, presumably you were able to get the tutorial/HelloWorld widget to work (from chapter 2) - that will also have used the same "tutorial" package. I'm a bit confused as to how one could have been found but not the other.

**Comment by angelborroy** [comment]
I've took first chapters some weeks ago, so I've decided to start from Chapter 6 today. Hence, package location at surf.xml described in https://github.com/Alfresco/Aikau/blob/master/tutorial/chapters/Tutorial2.md#step-1-adding-a-new-package was skipped for me.

Thanks for your time.

**Comment by kavithagundadi** [comment]
Hi I have created UserAndService.js file as suggested in the tutorial. After creating the Group,nothing is Displayed  on the page even after refreshing. 
i have followed the step
"https://github.com/Alfresco/Aikau/blob/master/tutorial/chapters/About.md".
