### ISSUE TITLE
Attribute bugs for 'alfresco/forms/controls/Select' control

### ISSUE THREAD

**Issue by ruria** [Alfresco/Aikau#226]
I´ve built a form dialog with a select control inside. I followed https://github.com/Alfresco/Aikau/blob/master/tutorial/chapters/Tutorial8.md#step-5-add-a-user-select-control tutorial but I had to hack to get this working. My control grab data from my own service so i´ve confiured this way:

```javascript
{
		   name: "alfresco/forms/controls/Select",
		   config: {
			  fieldId: "accountingHouseOptions",
		      label: "Asesoria",
		      description: "create_new_business_site.accountingHouseParent.label",
		      name: "accountingHouseParent",
		      optionsConfig: {
		    	  publishTopic: "ZZ_GET_AVAILABLE_ACCOUNTING_HOUSE_OPTIONS",
		    	  publishPayload: {valueSubscriptionTopic: "ZZ_SET_AVAILABLE_ACCOUNTING_HOUSE_OPTIONS"},
			  labelAttribute: "shortName"
			  valueAttribute: "shortNameValue"
		    	  //valueSubscriptionTopic: "ZZ_SET_AVAILABLE_ACCOUNTING_HOUSE_OPTIONS"
		      }
		   }
		};
```
To make this work:

1. valueSubscriptionTopic doesn´t work, I had to get the correct one from "payload.responseTopic" inside my service and publish it when 'options' done.
2. valueAttribute: doesn´t work (labelAttribute does) I think because   getValue: function alfresco_forms_controls_BaseFormControl__getValue() {..} is defaulting the attribute name in the payload to look for (it has to be 'value') So if I publish a payload with  option values in "value" attribute, it works.
3. labelAttribute has to be an optionsConfig child, not publishPayload as in tutorial.

**Comment by draperd** [comment]
Can you confirm which release of Aikau you're trying this out on please? 

When you say that the "valueSubscriptionTopic" attribute isn't working - have you checked that you're publishing at the correct scope? The "alfresco/forms/Form" widget will generate a "pubSubScope" attribute by default that the form controls will inherit. Use the "alfresco/logging/SubscriptionLog" (or on more recent versions of Aikau, the "alfresco/logging/DebugLog" to check what subscriptions and publications are occurring.

When you say that "valueAttribute" doesn't work - are you sure that you're publishing options that contain that attribute? 

The "labelAttribute" in the publishPayload is being used by the OptionsService in this case (to indicate what attribute in the REST API response to use as the label in the generated options. It is true that you can also set "labelAttribute" on the "optionsConfig" object to determine what attribute in the published options payload to use as the label.

Have you tried following the tutorial through as described? It's possible that there is an issue or some clarification that needs to be made, but quite a few people have successfully been through it now without reporting any issues.

**Comment by ruria** [comment]
Hi Dave, today double check it with Aikau 1.0.17, nothing changes for me.

"valueSubscriptionTopic" I think is not a scope problem, the event fire, and the control is subscribed to it. I´ve tried outside a form/dialog control (without scopes) and the same happens to me (see https://gist.github.com/ruria/5ba7db85f8df50b97e45 and https://gist.github.com/ruria/0400cc78b52e8733eca6) In "alfresco/logging/DebugLog" I can see select control is subscribed to "7aefdc8a-5bbb-4cd5-8e2c-efc5f8246531" topic, instead of "ZZ_SET_OPTIONS"

"valueAttribute": I manage to configure a select control with the same valueAtrribute and labelAttribute, when click on drop-down button, options (labels) are displayed, but no "current" value is on then control when selecting one of them.

"labelAttribute": That´s ok, good to know differences between both.

I walked throuth the tutorial (really great job, the tutorial itself and Aikau framework) but I can´t see and complete example of a select control + custom service, so I did my best effort ;-)

**Comment by draperd** [comment]
An example of using the "valueSubscriptionTopic" can be found on [this unit test page](https://github.com/Alfresco/Aikau/blob/master/aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/forms/controls/BaseForm.get.js)
 
The unit test that drives it is [here](https://github.com/Alfresco/Aikau/blob/master/aikau/src/test/resources/alfresco/forms/controls/BaseFormTest.js) (and it's passing)

You can try out the unit test page by opening this URL in a browser (http://localhost:8089/aikau/page/tp/ws/BaseForm) after cloning the Aikau GitHub repo and running:

```
mvn install jetty:run
```

From in the "aikau" directory.

The reason that you see the subscribed topic for options is that a UUID is generated as the topic to guarantee sender/recipient between the form control requesting the options and the service providing them. 

The main thing that stands out in your example is that you've got the same topic "ZZ_SET_OPTIONS" for both setting the value and requesting options which is definitely going to cause issues. 

But it looks like your service is publishing using the responseTopic generated so the options should get published. 

Thanks for the kind words about the tutorial and the framework - I appreciate the feedback, and hopefully I'll be able to help you through this issue that you're having.

**Comment by ruria** [comment]
Ok, I got it, very useful the BaseFormControl test, I didn´t see it.
My problem, I was including "valueSubscriptionTopic" as "optionsConfig" attribute instead as "config" attribute.

Thanks a lot!

PD: I´m using "ZZ_SET_OPTIONS" for setting the value and "ZZ_GET_OPTIONS" for requesting that is working fine.

**Comment by draperd** [comment]
Good to hear that you've resolved your problem. Thanks for using Aikau.
