### ISSUE TITLE
Manage aspects action

### ISSUE THREAD

**Issue by rderooij** [Alfresco/Aikau#299]
Hi,

I configured the ManageAspects action:

		name : "alfresco/renderers/PublishAction",
		config : {
			label : "Manage Aspects",
			publishTopic : "ALF_SINGLE_DOCUMENT_ACTION_REQUEST",
			publishPayloadType : "PROCESS",
			publishPayloadModifiers : [ "processCurrentItemTokens" ],
			publishPayload : {
				action : "onActionManageAspects",
				document : "{node}"
			}
		}

The dialog will not open because the nodeRef contains '://'. In the ManageAspectsService, the following code is used for node retrieval: 

      onAspects: function alfresco_services_actions_ManageAspectsService__onAspects(item) {
         this.serviceXhr({url: AlfConstants.PROXY_URI + "slingshot/doclib/aspects/node/" + item.nodeRef,
                          method: "GET",
                          item: item,

**Comment by draperd** [comment]
Thanks for raising this issue... I've created https://issues.alfresco.com/jira/browse/AKU-370 which will be included in our next weekly sprint that starts tomorrow (so you should hopefully see a fix delivered in Aikau version 1.0.23).

In the meantime, one way in which you could temporarily resolve your problem would be to apply the additional publishPayloadModifier "convertNodeRefToUrl" which should be added after the "processCurrentItemTokens" processor.

It's still relatively early days for us in working through all the existing Document Library actions in Aikau, but we appreciate you trying them out and reporting any issues that you do find.

**Comment by rderooij** [comment]
Thank you for the quick response. I really appreciate it. When I changed it as you recommended the action is gone.  I see no errors. When I undo my changes. It is available again. 

		name : "alfresco/renderers/PublishAction",
		config : {
			label : "Manage Aspects (includes current aspects)",
			publishTopic : "ALF_SINGLE_DOCUMENT_ACTION_REQUEST",
			publishPayloadType : "PROCESS",
			publishPayloadModifiers : [ "processCurrentItemTokens", "convertNodeRefToUrl" ],
			publishPayload : {
				action : "onActionManageAspects",
				document : "{node}"
			}
		}

**Comment by draperd** [comment]
Do you get any errors using that additional "convertNodeRefToUrl" processor? Also, what version of Aikau are you using?

**Comment by draperd** [comment]
The fix is now available in the 1.0.23 release

**Comment by SanjayBandhniya** [comment]
Hi,
I want to add custom action in Aikau Search Result page. Can you guide me how to add?
