### ISSUE TITLE
Search Result Bulk Download

### ISSUE THREAD

**Issue by anooj-monu** [Alfresco/Aikau#357]
Hi Dave,

I have customized the search page by creating a new webscript with name Custom Search.
In that page I have added a selector and a select items menu list.
i have also added a service which includes the download functionality
but my functionality is not working as per the requirement
 The changes are as follows
I made chenges in 
1.The custom-search.js page which is the replace for faceted-search.js
2. CustomSearchResult.js which is the replace for AlfSearchResult.js
3. CustomSearchResult.html which is the replace for  AlfSearchResult.html
4.The service file which I'm calling inside the custom-search.js
I made all these made follow the aikau tutorial for UsersAndGroups 
Please help me out 

![capture3](https://cloud.githubusercontent.com/assets/12935725/8470745/a917f558-20ad-11e5-92ce-a939f559bd4a.JPG)
![capture4](https://cloud.githubusercontent.com/assets/12935725/8470741/a8b5ec0a-20ad-11e5-80e1-71ce80b7bbc5.JPG)
![capture5](https://cloud.githubusercontent.com/assets/12935725/8470744/a8bd5620-20ad-11e5-94fb-3845a09769b7.JPG)
![capture6](https://cloud.githubusercontent.com/assets/12935725/8470743/a8b9eea4-20ad-11e5-8986-c57390719780.JPG)
![capture1](https://cloud.githubusercontent.com/assets/12935725/8470742/a8b7d862-20ad-11e5-96ea-62f233be2e62.JPG)
![capture2](https://cloud.githubusercontent.com/assets/12935725/8470740/a8adcaf2-20ad-11e5-8d7e-27a5e6f02e67.JPG)

**Comment by draperd** [comment]
OK, thanks for raising this issue... I'll look into it, but in the meantime perhaps you could let me know what versions of Alfresco and Aikau are you using? 

Also, in future it would be better if you could copy and paste the code into the issue (GitHub markdown provide some simple ways to format code) to make it easier to follow or test out for myself.

**Comment by draperd** [comment]
A couple of points looking at the screenshots you've posted... it looks like you've created a new page by simplying copy/pasting the existing faceted-search code... that's not really a good way to go about this, you'd be better of creating an extension module to just add/remove or reconfigure existing widgets in the page model (this blog post shows an easy way of customizing the faceted search page: http://blogs.alfresco.com/wp/developer/2015/04/01/adding-views-to-filtered-search/).

If you want to create a new page from an existing one, you can imply import the existing faceted-search.get.js file into your own WebScript controller and then manipulate the model that it creates.

**Comment by draperd** [comment]
Also... you haven't actually described what the problem you're facing is !! Could you please add some information on what is going wrong? I'd also suggest that you re-implement what you're doing as an extension described above - best to start by following the correct approach.

**Comment by anooj-monu** [comment]
Thanks for the reply
i'm using Alfresco 5.0.1 Enterprise version Aikau 1.0.8.2
My problem is I have created a service in which download functionality is added 
This download functionality is added in the selected item drop down But i'm unable to call it.
Don't know whats going wrong

**Comment by draperd** [comment]
Have you tried using the "Show Pub/Sub Log" option in the "Debug Menu" in Share to see whether or not you have your subscriptions and publications matched? e.g. is it possible that you're publishing a scoped request and subscribing to a global request? That is probably the most likely cause of the problem.

Also, it might be worth adding a break point into your own service to see if your function is getting called as a result of a publication.

**Comment by anooj-monu** [comment]
Do we have  "Debug Menu" option in Alfresco 5.0.1

**Comment by draperd** [comment]
Yes, but Share needs to be running in debug mode... you can do this by editing the "share-config.xml" file (found in share/WEB-INF/classes/alfresco) and setting <client-debug> to be true. When you restart Share you will see the Debug Menu

**Comment by anooj-monu** [comment]
I have changed the <client-debug>true</client-debug> in "share-config.xml" file .
but I could see no change in my tool bar.
what could be the problem
I have even restated the server Twice still no change
:(

**Comment by anooj-monu** [comment]
"<client-debug>true</client-debug>"

**Comment by anooj-monu** [comment]
![capture](https://cloud.githubusercontent.com/assets/12935725/8474536/6b035714-20ce-11e5-9aac-35f03eceac3b.JPG)

**Comment by draperd** [comment]
If you read the blog post I previously referenced (http://blogs.alfresco.com/wp/developer/2015/04/01/adding-views-to-filtered-search/) it has a link to the Alfresco instructions on how to set this up (http://docs.alfresco.com/5.0/tasks/dev-extensions-share-tutorials-debugging.html) I suggest you follow those instructions.

**Comment by anooj-monu** [comment]
In the pub/sub log my topic is getting publish but it is not getting subscribed.

**Comment by anooj-monu** [comment]
![capture7](https://cloud.githubusercontent.com/assets/12935725/8476644/fccffae6-20e0-11e5-9295-8cc3e6b4d3c5.JPG)

**Comment by draperd** [comment]
Have you checked to see if the source for your BulkExportService is being included in the page? If so, set a breakpoint on it to check that it is setting up the subscritpion

**Comment by anooj-monu** [comment]
Sorry to ask this silly question but i have never used breakpoints in alfresco.
Can you please suggest me how to do that.
Thanks in advance

**Comment by draperd** [comment]
I mean in your browser.... e.g. if you're using Chrome then hit the F12 key to get the developer tools, click on the "Sources" tab, use CTRL-P to search for files, type "surf", the highlighted file will be the aggregated Aikau resources, hit enter to view that file... use CTRL-F to find a line of your code.... if it's not there, then your code hasn't been included on the page

**Comment by anooj-monu** [comment]
No my service file is not being included in that surf file.
But the method of adding that is the same as other services
I have included  my service inside service.push method

**Comment by draperd** [comment]
Are you sure your service is located in the correct location? Have you packaged it correctly? Are you getting any errors in the server stdout to indicate that the file can't be displayed?

**Comment by anooj-monu** [comment]
No any such errors. I have followed the aikau tutorial "https://github.com/Alfresco/Aikau/blob/master/tutorial/chapters/Tutorial8.md" . as i tired to extend the widget it wasn't wrkng as per the requirement then i maintained the same hierarchy js/aikau/1.0.8.2/alfresco/services/UserAndGroupService It was working fine. The service was being included in my page . So i followed the same procedure on search to include my service but it is not getting included don't know were my code is going wrong.

**Comment by anooj-monu** [comment]
That error is resolved now my service file is getting included into the surf page. Thanks for your valuable time. Last question can u suggest me few of the services to be included in my custom service which helps me to download documents and folder on search page. As per my knowledge I'm trying to include ActionService and DocumentService.

**Comment by anooj-monu** [comment]
I have added a publish topic inside my bulk export 
but when i'm checking my selector on my page and clicking on bulk export button i'm getting 2 errors
![typeerror](https://cloud.githubusercontent.com/assets/12935725/8493941/90c63aca-217d-11e5-9eb3-e7b426e6a106.JPG)

 {
                 	   name: "alfresco/documentlibrary/AlfSelectedItemsMenuBarPopup",
                 	   config: {
                 	      passive: false,
                 	      itemKeyProperty: "nodeRef",
                 	      label: "Selected items...",
                 	      widgets: [
                 	         {
                 	            name: "alfresco/menus/AlfMenuGroup",
                 	            config: {
                 	               widgets: [
                 	                  {
                 	                     name: "alfresco/menus/AlfSelectedItemsMenuItem",
                 	                     config: {
                 	                        label: "Bulk Export",
                 	                        clearSelectedItemsOnClick: true,
                 	                       publishTopic: "ALF_DOWNLOAD_FILE"
                 	                       
                 	                     }
                 	                  }
                 	               ]
                 	            }
                 	         }
                 	      ]
                 	   }
                 	}

**Comment by draperd** [comment]
I would suggest that you click on the link in the Developer tools window that is reporting the error. I suspect that this is an error somewhere in your service and you will need to debug that. Also, you're trying to implement something that is not supported out-of-the-box in Aikau and haven't actually reported any bugs with any of the Aikau code. 

Is there any actual bug in Aikau that you want to report? As I think that this issue should now be closed. We're very happy to help with resolving Aikau issues but this is turning into a general JavaScript progreamming/debugging lesson.

**Comment by anooj-monu** [comment]
Thanks for your time.
