### ISSUE TITLE
An easier way to replace browserTitlePrefix for all pages

### ISSUE THREAD

**Issue by douglascrp** [Alfresco/Aikau#427]
I tried to replace the faceted-search page's title:
```
var pageTitleWidget = widgetUtils.findObject(model.jsonModel.widgets, "id", "HEADER_TITLE");
 
if(pageTitleWidget != null){
    pageTitleWidget.config.browserTitlePrefix = msg.get("faceted.search.page.custom.title.prefix");
}
```
This code works, but then I have to repeat the same thing for the search config form, and I guess, for all new pages built with Aikau.
Is there any easier way of doing that? Something like we used to do replacing the property "page.title" ?

**Comment by draperd** [comment]
No, unfortunately not... however, would be just one extension that is applied to all modules across Share (you'd need to set up your module configuration correctly for both Aikau and legacy pages, but they'd all use the same header model - see http://forums.alfresco.com/forum/developer-discussions/web-scripts/share-headergetjs-extension-override-doesnt-always-work).

**Comment by draperd** [comment]
I'm not sure there's anything that can be done within the Aikau code base so I'm closing this
