### ISSUE TITLE
Button Emabling

### ISSUE THREAD

**Issue by anooj-monu** [Alfresco/Aikau#428]
I have used Alfbutton widget in one of my dialog box.
While Initializing the button i have set the disabled property to true.
I need to set the same disabled property to false once I get my response.
Here I have tried by changing  widgetsbuttons.config.disabled=false
but my button is not getting enabled any suggestions on how to enable the button

**Comment by anooj-monu** [comment]
var dialog1 = new AlfDialog({


widgetsButtons: [
									   {
											name: "alfresco/buttons/AlfButton",
											config: {
											  label: "Download",
											  publishTopic:"GET_All_SELECTED_ASPECTS",
											  publishPayload: lang.clone(payload),
											  disabled:true
											}
										},
										{
											name: "alfresco/buttons/AlfButton",
											config: {
											  label: "Select All",
											  publishTopic: "SELECT_ALL"

											}
										},
										{
											name: "alfresco/buttons/AlfButton",
											config: {
											  label: "Clear All",
											  publishTopic: "CLEAR_ALL"
											}
										},
										{
											name: "alfresco/buttons/AlfButton",
											config: {
											  label: "Cancel",
											  publishTopic: "NOOP"
											}
										}
									]


dialog1.widgetsButtons[0].config.disabled=false;

**Comment by anooj-monu** [comment]
this is my code snippet 
But still button is not enabled
please suggest me how to enable the button

**Comment by draperd** [comment]
It might be better if you provided some context as to what you're trying to do.... e.g. if you want your button to be enabled, then why disable it in the first place? What should user activity should result in your button becoming enabled? Are you using the DialogService (as is recommended).  At the moment the AlfButton is only setup to dynamically enable/disable when used in relation to a alfresco/form/Form. If you're not using a form then at the moment you might want to either extend to create a custom button that handles enabling/disabling as you require.

**Comment by anooj-monu** [comment]
The button should be disabled as the content that the dialog displays takes some time to generate .I need to display the dialog 1st then the user waits for the content to appear completely and then the dialog button gets enabled. When the button is clicked the complete data gets transmitted to the server queue. Hope I'm clear with what actually going on behind this. Please suggest me what need to be done .

**Comment by draperd** [comment]
What sort of content is in the dialog? Using the DialogService to create a form dialog will leverage the benefits of the Aikau forms infrastructure to automatically control the enablement of the button, this would require that you use form controls in the dialog (but you could always create your own by extending the alfresco/forms/controls/BaseFormControl module). Alternatively you could extend the alfresco/buttons/AlfButton widget to handle your particular requirements and then pass those buttons into the DialogService via the "widgetsButtons" attribute.

**Comment by anooj-monu** [comment]
dialog appears when i select few files .
Inside Dialog I have a picker which includes some items(not the files which are selected).
inside dialog i need to even display the count of the files which are selected before the dialog.
that count comes from a service response which takes some time. Now I want  to disable the button till i get my count.

**Comment by draperd** [comment]
Ok... my previous answer applies. Either extend the alfresco/buttons/AlfButton to get the exact enable/disable functionality that you require. Or extend alfresco/forms/controls/BaseFormControl for your counter and allow the form infrastructure to take care of the button enable/disable state.

**Comment by anooj-monu** [comment]
Resolved thanks I have changed my approached.
