### ISSUE TITLE
Not possible to open searchresultLink in new tab

### ISSUE THREAD

**Issue by HansDeBal** [Alfresco/Aikau#586]
Hi,

I customized the share advanced-search-page to be able to search on custom object-types. In the resultpage I created a table view and I want to make the link behind the document-name to open in a new page. According to the documentation, this should be possible (alfresco/services/_NavigationServiceTopicMixin.newTarget) and alfresco/services/NavigationService.navigateToPage

`
else if (data.target === this.newTarget)
               {
                  window.open(url);
               }
`

However, when you look at alfresco/renderers/_SearchResultLinkMixin.generateSearchLinkPayload the following is hardcoded and not merged with the publishPayload entered while instantiating the widget
`
var payload = {
            type: "PAGE_RELATIVE",
            target: "CURRENT",
            url: null
         };
`

There is no way to overwrite this setting

**Comment by draperd** [comment]
What version of Aikau are you using?

**Comment by HansDeBal** [comment]
The one standard in Alfresco One 5.0.2.1

**Comment by draperd** [comment]
Yes, you're quite right... this should be a configurable attribute (as should the navigation type). I've raised the following JIRA issue to address this: https://issues.alfresco.com/jira/browse/AKU-611

As this is a relatively minor change we should be able to include this in the next sprint so it should be included in the 1.0.39 release.

**Comment by draperd** [comment]
This has been implemented and is pending review and merge for inclusion in the 1.0.39 release. In order to use the new capability you'll need to configure the AlfSearchResult so that "navigationTarget" is "NEW" (note: this will effect all links - e.g. the site, display name, creation/modification date, etc).

See the unit test page for an example.

1.0.39 should be released on the 14th October

**Comment by draperd** [comment]
This has now been resolved.
