### ISSUE TITLE
I have a problem with editing association of a datalist.

### ISSUE THREAD

**Issue by M-Thirumal** [Alfresco/Aikau#592]
I am trying to create a custom page in alfresco using Aikau to list and edit dataLists.

I have created a custom dataList, which takes another custom dataList as its association(multiplicity 1:1). This association is mandatory. 

I am able to edit the properties of datalist by the help of the webscript "api/{item_kind}/{item_id}/formprocessor" (item_kind = node, item_id = nodeRef). But I am not able to change the associations. 

Is there any inbuilt function to edit association? 

Thanks in advance.

**Comment by draperd** [comment]
We haven't created any widgets yet that can be used to edit associations. If you just need to get the NodeRef of the document that you wish to create the association with then you can probably use the existing alfresco/forms/controls/DocumentPicker widget.

**Comment by M-Thirumal** [comment]
Thanks for your reply.
I'm using alfresco/forms/controls/DojoSelect. I'm able to get the nodeRef and add association to dataList too. But I'm not able to change it. It is giving following error when I tried to change association :

"The association target multiplicity has been violated: 
   Source Node: workspace://SpacesStore/74c70cf0-b357-4589-b08b-db2ce4528510
   Association: Association[ class=ClassDef[name={http://essg/model}artifactDatalist], name={http://essg/model}eventAssociation, target class={http://essg/model}eventDataList, source role=null, target role=null]
   Required target Multiplicity: 1..1
   Actual target Multiplicity: 2"

**Comment by draperd** [comment]
I'm not sure how this is an Aikau question then? This appears to be an issue you're having with the Alfresco Repository?
