### ISSUE TITLE
Render filter issue

### ISSUE THREAD

**Issue by KumarGovindh** [Alfresco/Aikau#610]
We are creating a custom page using Aikau for custom datalists. We are able to add and remove the custom datalist items. We have been able to provide edit functionality also but only for properties. We are facing problem while editing associations.
In this case associations are other datalist items. To accomplish this we are using edit form dialog and "api/node/{nodeRef}/formprocessor" as formSubmissionPayloadMixin URL. We are rendering "alfresco/forms/controls/DojoSelect" to add the association. Depending on the add form control value attribute we are rendering the form control to remove the association. 

renderFilter: [{
       				target: "",
        			property: "value",
        			renderOnAbsentProperty: true,
        			values: ["no"]
      			}]
This is the render filter we are using to remove association. If the association is not changed during edit then the remove form control should not be rendered. We are not sure what value to use in the target attribute. We know the add form control widgetId. What could be the value for target attribute?

**Comment by draperd** [comment]
It looks like you've already asked a related question on the Alfresco blogs, that I've answered here:https://www.alfresco.com/blogs/developer/2014/09/26/aikau-mini-examples-role-based-rendering/#comment-201470

First of all, you should probably be aware that alfresco/forms/controls/DojoSelect is deprecated and you should be using alfresco/forms/controls/Select (to future proof your implementation)... deprecations are listed both in the release notes (https://github.com/Alfresco/Aikau/blob/master/aikau/ReleaseNotes.md) and in the JSDoc (http://dev.alfresco.com/resource/docs/aikau-jsdoc/DojoSelect.html).

If you're looking to achieve dynamic visibility (e.g. you want the form control to be dynamically appear or disappear with changes to other fields in the form) then you should be using visibilityConfig.

If you are using the renderFilter configuration then you need to be evaluating properties of the widget itself, typically this based on the "currentItem" being rendered... for more information on how to use renderFilter you should review this tutorial chapter: https://github.com/Alfresco/Aikau/blob/master/tutorial/chapters/Tutorial15.md

**Comment by draperd** [comment]
Closing as there is no bug reported to fix.
