### ISSUE TITLE
Title in head does not display correctly for i18n and umlauts

### ISSUE THREAD

**Issue by loftux** [Alfresco/Aikau#654]
I've notice that title in html head (`<head><title>`) does not display correctly for aikau based pages.
Pages that are "old" Surf pages shows correctly.

For example the search page should show `"Sök"` in Swedish, but is shown as `"S&ouml;k"`.
All localisation properties files are encoded for umlauts, and it shows correctly in all other parts of an aikau page.

If needed I can provide you with the Swedish localization amps.
I've tested this with 5.1.c now, but it is the same for 5.0 Community versions as well.

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/AKU-685 to cover this and it will be included in the next sprint (Sprint 44) so can be expected to be resolved in the 1.0.44 release.

As a general aside we'd prefer to be in a position of double-encoding over no encoding from a security point of view. However, that said we obviously want to resolve this issue satisfactorily. 

Also, whilst this will be included in an Aikau release, there's no guarantee that this will be included in Alfresco 5.1 so you may want to raise an issue against Alfresco for PM to prioritize this as an essential issue to be resolved in the 5.1 release.

**Comment by draperd** [comment]
This has now been fixed in the 1.0.43 release - however, as previously stated - this does not mean that it is fixed in any particular release of Alfresco Share.

**Comment by draperd** [comment]
Peter... I see you made this comment in the IRC logs: 

> <Loftux> ohej: Yes just got a notification. I guess it will be in next release of Share.

...you might want to note my previous comments. This is a fix in Aikau, not Share.

**Comment by loftux** [comment]
Yes, I got that is a fix in Aikau, but I guess it will eventually make it into Share when the dependency is updated to use the 1.0.43. Or that I can update the dependency myself if I need it faster than next release of Share. Stil have some catching up to do in terms of how to build 5.1 after the split of source code, think it is an improvement, just unfamiliar compared to when everything was in one place.

**Comment by draperd** [comment]
OK, I just wanted to check - my point being that bugs are triaged for inclusion in 5.1 by a Product Management team (because we're now so close) so I can't just upgrade Share to use 1.0.43 for the 5.1 release.
