### ISSUE TITLE
Tutorial 17 documentation wrong value

### ISSUE THREAD

**Issue by teqnology** [Alfresco/Aikau#675]
Hi,

just pointing out a typo in the documentation where: *Add a new `alfresco/layout/HorizontalLayout` into the page and place the `alfresco/documentlibrary/AlfDocumentList` as the first widget into the widgets array of its configuration.*

The `HorizontalLayout` is maybe meant to be `HorizontalWidgets`?

Thanks.

**Comment by draperd** [comment]
You're absolutely right - thank you for going to the trouble of reporting this, I'll get it fixed today.

**Comment by draperd** [comment]
The tutorial change has been merged to the "develop" branch - so after the next release (next Tuesday) the change will be reflected on the "master" branch.

**Comment by teqnology** [comment]
Thanks for the update.
