### ISSUE TITLE
CheckBox value issue

### ISSUE THREAD

**Issue by KumarGovindh** [Alfresco/Aikau#722]
Hi,

I am using the following checkBox widget in the form dialog:

```javascript
editPropertiesAndAssociations.push({
   name: "alfresco/forms/controls/CheckBox",
   config: {
      name: "prop_" + property.name.replace(type + ":", type + "_"),
      label: "{itemData.prop_" + property.name.replace(type + ":", type + "_") +
         ".displayValue}",
      value: "{itemData.prop_" + property.name.replace(type + ":", type + "_") +
         ".displayValue}"
   }
});
```

If the checkbox config value is `value: false`, the dialog checkBox will be in uncheck state its fine but the problem is when I assign value as `value: "{itemData.prop_" + property.name.replace(type + ":", type + "_") + ".displayValue}"` then the checkbox is always in check state its doesn't considering the given value and I checke the value of  `"{itemData.prop_" + property.name.replace(type + ":", type + "_") + ".displayValue}"` by assigning it into lable.

do you have any suggestion.

Thanks
kumar

**Comment by draperd** [comment]
Value needs to either be true or false. It doesn't act like an HTML checkbox... it is a widget that can be used to indicate true/false and nothing else.
