### ISSUE TITLE
Problem setting up test environment on windows

### ISSUE THREAD

**Issue by yregaieg** [Alfresco/Aikau#783]
I am starting to experiment on aikau unit testing. 

After few unsuccessful local trials I came to understand that local test are not reliable, I am now trying running the tests against a VirtualBox VM, and I am hitting these errors:

	  ====================================

	   AIKAU UNIT TESTS (Ctrl-C to abort)
	  ====================================
	  FAILED

	  [previous messages h/dden ...]
	  PROGRESS                                   STATUS                       LAST STARTED TEST
		- Test Previous Page Button Disables (on scroll) [Chrome v47.0.2526.111 on Linux]
												 Requested Envs: 2            Environment: Complete
		- Test Link Value [Chrome v47.0.2526.111 on Linux]
	  ----------------------------------------   Tested Envs:    1            Suite name:  Complete
		- Test Find Next [Chrome v47.0.2526.111 on Linux]
	  ====================....................   Total tests:    4524         Test name:   Complete
	  Download as ZIP Action Tests
	  ----------------------------------------   Passed:         2248 (49.7%)

												 Failed:         12 (0.3%)    REPORTER INFO
	  ERRORS
	  Percent complete: 50%                      Skipped:        2 (0.0%)     Last called method: runEnd
	  N/A
	  Tunnel status:    Active                   Errors:         1

	  Time taken:       36 minutes 14 seconds    Warnings:       1

	  Time Remaining:   40 mins remaining        Deprecations:   0

	  DEPRECATIONS
	  FAILED
	  N/A
	  ========================================
		- Test Thumbnail Navigation [Chrome v47.0.2526.111 on Linux]
		- Test Link Value [Chrome v47.0.2526.111 on Linux]
		- Test First Page is active [Chrome v47.0.2526.111 on Linux]
		- Test Find Next [Chrome v47.0.2526.111 on Linux]
		- Test Find Previous [Chrome v47.0.2526.111 on Linux]
	  Download as ZIP Action Tests
		- Test non-legacy action version [Chrome v47.0.2526.111 on Linux]

	  ERRORS

	  firefox on any platform (Unknown)
		- [POST http://192.168.56.4:4444/wd/hub/session / {"desiredCapabilities":{"browserName":"firefox","selenium-version":"2.44.0","name":"src/test/resources/intern",...

	  WARNINGS

	  "firefox on any platform"
		- Unable to retrieve environment info

	  DEPRECATIONS

	  N/A

	========================
	===== ENVIRONMENTS =====
	========================

	"Chrome on any platform" was fulfilled by "Chrome v47.0.2526.111 on Linux"
	"Firefox on any platform" was fulfilled by "true"

	====================
	===== FAILED =====
	====================

	--- Chrome v47.0.2526.111 on Linux ---

	Inherited DND Configuration Tests
	"Check prepopulated nested widget configuration"
	[POST http://192.168.56.4:4444/wd/hub/session/db84cbf8-dd35-49a1-b8d0-f0bd2e3440a8/element/326/click] unknown error: Element is not clickable at point (829, 232). Other element would receive the click: <div class="dijitDialogUnderlay _underlay" tabindex="-1" data-dojo-attach-point="node" id="ALF_DROPPED_ITEM_CONFIGURATION_DIALOG_underlay" style="width: 1009px; height: 661px;"></div>
	  (Session info: chrome=47.0.2526.111)
	  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux 3.13.0-74-generic x86_64) (WARNING: The server did not provide any stacktrace information)
	Command duration or timeout: 33 milliseconds
	Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
	System info: host: 'vagrant-ubuntu-trusty-64', ip: '10.0.2.15', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-74-generic', java.version: '1.7.0_91'
	Session ID: 8b34468d354a52aa008706a3722e94da
	Driver info: org.openqa.selenium.chrome.ChromeDriver
	Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.TjbO5y}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=47.0.2526.111, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]

	Site Picker Tests
	"Can choose single site"
	[POST http://192.168.56.4:4444/wd/hub/session/db84cbf8-dd35-49a1-b8d0-f0bd2e3440a8/element/1223/click] unknown error: Element is not clickable at point (551, 276). Other element would receive the click: <div data-dojo-attach-point="viewsNode" data-aikau-loading-message="Loading..." data-aikau-rendering-message="Please wait while the view is rendered..." class="alfresco-lists-AlfList__views rendered-view">...</div>
	  (Session info: chrome=47.0.2526.111)
	  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux 3.13.0-74-generic x86_64) (WARNING: The server did not provide any stacktrace information)
	Command duration or timeout: 37 milliseconds
	Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
	System info: host: 'vagrant-ubuntu-trusty-64', ip: '10.0.2.15', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-74-generic', java.version: '1.7.0_91'
	Session ID: 8b34468d354a52aa008706a3722e94da
	Driver info: org.openqa.selenium.chrome.ChromeDriver
	Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.TjbO5y}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=47.0.2526.111, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]
	"Can choose multiple sites"
	[POST http://192.168.56.4:4444/wd/hub/session/db84cbf8-dd35-49a1-b8d0-f0bd2e3440a8/element/1224/click] unknown error: Element is not clickable at point (536, 43). Other element would receive the click: <div class="dijitDialogUnderlay _underlay" tabindex="-1" data-dojo-attach-point="node" id="6050c889-6405-4249-82a5-41107c6addfb_underlay" style="width: 1009px; height: 661px;"></div>
	  (Session info: chrome=47.0.2526.111)
	  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux 3.13.0-74-generic x86_64) (WARNING: The server did not provide any stacktrace information)
	Command duration or timeout: 39 milliseconds
	Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
	System info: host: 'vagrant-ubuntu-trusty-64', ip: '10.0.2.15', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-74-generic', java.version: '1.7.0_91'
	Session ID: 8b34468d354a52aa008706a3722e94da
	Driver info: org.openqa.selenium.chrome.ChromeDriver
	Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.TjbO5y}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=47.0.2526.111, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]

	List Local Storage (2)
	"When there is no hash, the current filter is set as the hash"
	The URL hash was not set to the current filter: expected 'http://192.168.56.1:8089/aikau/page/tp/ws/ListLocalStorageFallback?listType=CurrentFilterWithLocalStorage#key1=value1&key2=value2' to include '#key2=value2&key1=value1'

	Local Storage for Lists Tests (5)
	"When there is no hash and local storage is available the current filter should still be used"
	Current filter was not used: expected 'http://192.168.56.1:8089/aikau/page/tp/ws/ListLocalStorageFallback?listType=CurrentFilter#key1=value1&key2=value2' to include '#key2=value2&key1=value1'

	PdfJs Previewer Tests
	"Test Previous Page Button Disables (on scroll)"
	The previous page button was not disabled when scrolling back to the top of the viewer
	"Test Thumbnail Navigation"
	The second page was not active after clicking it's thumbnail
	"Test Link Value"
	The link was not generated correctly: http://192.168.56.1:8089/aikau/page/tp/ws/PdfJsPreview#page=6
	"Test First Page is active"
	The first page was not active before starting find tests: expected [ depth: 1 ] to have a length of 1 but got 0
	"Test Find Next"
	The second page did not become the active page as we went to the next search result
	"Test Find Previous"
	The first page did not become the active page as we went to the previous search result

	Download as ZIP Action Tests
	"Test non-legacy action version"
	[POST http://192.168.56.4:4444/wd/hub/session/db84cbf8-dd35-49a1-b8d0-f0bd2e3440a8/element/3176/click] unknown error: Element is not clickable at point (40, 131). Other element would receive the click: <table class="dijit dijitReset dijitMenuTable dijitMenuActive dijitMenu dijitMenuFocused dijitFocused" role="menu" tabindex="-1" cellspacing="0" id="ACTIONS_ITEM_1_GROUP" widgetid="ACTIONS_ITEM_1_GROUP" style="top: 0px; visibility: visible;">...</table>
	  (Session info: chrome=47.0.2526.111)
	  (Driver info: chromedriver=2.15.322448 (52179c1b310fec1797c81ea9a20326839860b7d3),platform=Linux 3.13.0-74-generic x86_64) (WARNING: The server did not provide any stacktrace information)
	Command duration or timeout: 15 milliseconds
	Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:16:47'
	System info: host: 'vagrant-ubuntu-trusty-64', ip: '10.0.2.15', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-74-generic', java.version: '1.7.0_91'
	Session ID: 8b34468d354a52aa008706a3722e94da
	Driver info: org.openqa.selenium.chrome.ChromeDriver
	Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.TjbO5y}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=47.0.2526.111, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, applicationCacheEnabled=false, takesScreenshot=true}]

	====================
	===== SKIPPED =====
	====================

	--- Chrome v47.0.2526.111 on Linux ---

	Dashlet Tests
	"Resizing dashlet stores height"
	Test skipped because test environment is "chrome on any platform"

	Infinite Scrolling Dashlet Tests
	"Resizing first dashlet prompts data-load"
	Test skipped because test environment is "chrome on any platform"

	==================
	===== ERRORS =====
	==================

	firefox on any platform (Unknown)
	"[POST http://192.168.56.4:4444/wd/hub/session / {"desiredCapabilities":{"browserName":"firefox","selenium-version":"2.44.0","name":"src/test/resources/intern","idle-timeout":60}}] Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
	r GMPProvider
	1453308636586   addons.manager  DEBUG   Provider finished startup: GMPProvider
	1453308636586   addons.manager  DEBUG   Starting provider: PluginProvider
	1453308636586   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
	1453308636586   addons.manager  DEBUG   Provider finished startup: PluginProvider
	1453308636587   addons.manager  DEBUG   Completed startup sequence
	1453308636666   DeferredSave.extensions.json    DEBUG   Save changes
	1453308636667   addons.xpi      DEBUG   Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"qKhgLrEsEpoE","location":"app-profile","version":"2.46.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":false,"descriptor":"/tmp/anonymous4264647846486076396webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1453308636000,"updateDate":1453308636000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8445045,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
	1453308636667   addons.xpi      DEBUG   getModTime: Recursive scan of fxdriver@googlecode.com
	1453308636672   DeferredSave.extensions.json    DEBUG   Save changes
	1453308636672   addons.xpi      DEBUG   Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"qKhgLrEsEpoE","location":"app-profile","version":"2.46.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":true,"descriptor":"/tmp/anonymous4264647846486076396webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1453308636000,"updateDate":1453308636000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8445045,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
	1453308636730   addons.manager  DEBUG   Starting provider: <unnamed-provider>
	1453308636730   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
	1453308636730   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
	1453308636778   DeferredSave.extensions.json    DEBUG   Starting write
	1453308636881   addons.repository       DEBUG   No addons.json found.
	1453308636881   DeferredSave.addons.json        DEBUG   Save changes
	1453308636883   DeferredSave.addons.json        DEBUG   Starting timer
	1453308636893   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
	1453308636893   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
	1453308636893   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
	1453308636896   DeferredSave.extensions.json    DEBUG   Write succeeded
	1453308636896   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
	1453308636935   DeferredSave.addons.json        DEBUG   Starting write
	1453308636946   DeferredSave.addons.json        DEBUG   Write succeeded
	"
	[POST http://192.168.56.4:4444/wd/hub/session / {"desiredCapabilities":{"browserName":"firefox","selenium-version":"2.44.0","name":"src/test/resources/intern","idle-timeout":60}}] Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:
	r GMPProvider
	1453308636586   addons.manager  DEBUG   Provider finished startup: GMPProvider
	1453308636586   addons.manager  DEBUG   Starting provider: PluginProvider
	1453308636586   addons.manager  DEBUG   Registering shutdown blocker for PluginProvider
	1453308636586   addons.manager  DEBUG   Provider finished startup: PluginProvider
	1453308636587   addons.manager  DEBUG   Completed startup sequence
	1453308636666   DeferredSave.extensions.json    DEBUG   Save changes
	1453308636667   addons.xpi      DEBUG   Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"qKhgLrEsEpoE","location":"app-profile","version":"2.46.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":false,"descriptor":"/tmp/anonymous4264647846486076396webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1453308636000,"updateDate":1453308636000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8445045,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
	1453308636667   addons.xpi      DEBUG   getModTime: Recursive scan of fxdriver@googlecode.com
	1453308636672   DeferredSave.extensions.json    DEBUG   Save changes
	1453308636672   addons.xpi      DEBUG   Updating XPIState for {"id":"fxdriver@googlecode.com","syncGUID":"qKhgLrEsEpoE","location":"app-profile","version":"2.46.0","type":"extension","internalName":null,"updateURL":null,"updateKey":null,"optionsURL":null,"optionsType":null,"aboutURL":null,"iconURL":null,"icon64URL":null,"defaultLocale":{"name":"Firefox WebDriver","description":"WebDriver implementation for Firefox","creator":"Simon Stewart","homepageURL":null},"visible":true,"active":false,"userDisabled":false,"appDisabled":true,"descriptor":"/tmp/anonymous4264647846486076396webdriver-profile/extensions/fxdriver@googlecode.com","installDate":1453308636000,"updateDate":1453308636000,"applyBackgroundUpdates":1,"bootstrap":false,"size":8445045,"sourceURI":null,"releaseNotesURI":null,"softDisabled":false,"foreignInstall":true,"hasBinaryComponents":true,"strictCompatibility":false,"locales":[],"targetApplications":[{"id":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","minVersion":"3.0","maxVersion":"66.*"}],"targetPlatforms":[{"os":"Darwin","abi":null},{"os":"SunOS","abi":null},{"os":"FreeBSD","abi":null},{"os":"OpenBSD","abi":null},{"os":"WINNT","abi":"x86-msvc"},{"os":"Linux","abi":null}],"multiprocessCompatible":false,"signedState":0}
	1453308636730   addons.manager  DEBUG   Starting provider: <unnamed-provider>
	1453308636730   addons.manager  DEBUG   Registering shutdown blocker for <unnamed-provider>
	1453308636730   addons.manager  DEBUG   Provider finished startup: <unnamed-provider>
	1453308636778   DeferredSave.extensions.json    DEBUG   Starting write
	1453308636881   addons.repository       DEBUG   No addons.json found.
	1453308636881   DeferredSave.addons.json        DEBUG   Save changes
	1453308636883   DeferredSave.addons.json        DEBUG   Starting timer
	1453308636893   addons.manager  DEBUG   Starting provider: PreviousExperimentProvider
	1453308636893   addons.manager  DEBUG   Registering shutdown blocker for PreviousExperimentProvider
	1453308636893   addons.manager  DEBUG   Provider finished startup: PreviousExperimentProvider
	1453308636896   DeferredSave.extensions.json    DEBUG   Write succeeded
	1453308636896   addons.xpi-utils        DEBUG   XPI Database saved, setting schema version preference to 17
	1453308636935   DeferredSave.addons.json        DEBUG   Starting write
	1453308636946   DeferredSave.addons.json        DEBUG   Write succeeded

		at Server.createSession (C:\test\my-aikau\aikau\node_modules\intern\node_modules\leadfoot\Server.js:307:15)
		at C:/test/my-aikau/aikau/node_modules/intern/lib/executors/Runner.js:190:22
		at retry (C:/test/my-aikau/aikau/node_modules/intern/lib/util.js:723:13)
		at C:\test\my-aikau\aikau\node_modules\intern\node_modules\dojo\Promise.js:156:41
		at runCallbacks (C:\test\my-aikau\aikau\node_modules\intern\node_modules\dojo\Promise.js:19:22)
		at C:\test\my-aikau\aikau\node_modules\intern\node_modules\dojo\Promise.js:103:21
		at run (C:\test\my-aikau\aikau\node_modules\intern\node_modules\dojo\Promise.js:51:33)
		at C:\test\my-aikau\aikau\node_modules\intern\node_modules\dojo\nextTick.js:35:17
		at nextTickCallbackWith0Args (node.js:452:9)
		at process._tickCallback (node.js:381:13)

	====================
	===== WARNINGS =====
	====================

	"firefox on any platform"
	"Unable to retrieve environment info"

	Error: Run failed due to one or more suite errors
	  at emitLocalCoverage  <node_modules\intern\lib\executors\Executor.js:342:18>
	  at finishSuite  <node_modules\intern\lib\executors\Executor.js:359:15>
	  at <node_modules\intern\lib\executors\Executor.js:367:8>
	  at <node_modules\intern\node_modules\dojo\Promise.ts:393:15>
	  at runCallbacks  <node_modules\intern\node_modules\dojo\Promise.ts:11:11>
	  at <node_modules\intern\node_modules\dojo\Promise.ts:317:4>
	  at run  <node_modules\intern\node_modules\dojo\Promise.ts:237:7>
	  at <node_modules\intern\node_modules\dojo\nextTick.ts:44:3>
	  at nextTickCallbackWith0Args  <node.js:452:9>
	  at process._tickCallback  <node.js:381:13>
	Warning: Test failure; check output above for details. Use --force to continue.

	Aborted due to warnings.

	Execution Time (2016-01-20 16:13:32 UTC)
	waitServer:server   2m 14.8s  ████████ 6%
	intern:dev         36m 26.8s  █████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ 94%
	Total 38m 55.9s

My understanding is that errors are shown once we get to Firefox tests.

----------------

I understand that vagrant is running tests against a VirtualBox VM in headless mode. Is there a way to configure that VM to have more RAM/CPU cores to speed up tests ?

**Comment by draperd** [comment]
It's possible that we may need to update the configuration of the VM with relation to the Firefox version it installs as there may be an incompatibility with the Selenium drivers. As we don't often recreate our VMs we wouldn't have detected this issue.

I'll try and dig into this problem this week, I'm loathe to destroy my working VM mid-sprint though as it will disrupt my progress so I might need to defer this until next week.

**Comment by yregaieg** [comment]
Thank you for your quick response.And yes i can wait a week or two so no hurries. and if you can manage to upload a working vm for me i would appreciate that!

**Comment by draperd** [comment]
I've raised the following JIRA issue for this: https://issues.alfresco.com/jira/browse/AKU-793. I'll look into the problems in our next sprint.

**Comment by draperd** [comment]
As it happens, my machine died today and I've had to re-install my OS... I've hit the exact same issues on setting up, I think that there has to be an incompatibility problem with Firefox and Selenium... as soon as I've resolved the issue myself I'll let you know the solution

**Comment by draperd** [comment]
I've found a solution and have pulled the JIRA issue into the current sprint

**Comment by draperd** [comment]
You're likely to need to recreate the VM to get this working unfortunately.

**Comment by MartinDoyleUK** [comment]
We had some problems with this ourselves, where Chrome didn't run more than once, so we've updated the vagrant configuration files (more info at #792). On my local machine (OS X El Capitan), I've installed the latest VirtualBox (5.0) and a more recent Vagrant (1.7.4), and recreated the vagrant machine from scratch (delete the machine using VirtualBox and then run `grunt vcreate`).

These updates are going to be in Aikau 1.0.52 (to be released imminently), so please do give it a try when you're able. Hopefully it should all work perfectly, but please let us know if not.

**Comment by draperd** [comment]
Both Martin and I have now completely rebuild our VM images using the updated scripts with no issues. I'm actually still on VirtualBox 4.3 and Vagrant 1.8.
