### ISSUE TITLE
Missing service/constants/Default file.

### ISSUE THREAD

**Issue by muralidharand** [Alfresco/Aikau#787]
I am seeing the in /alfresco/core/Page.js file is referring **service/constants/Default** javascript, but I could not see the file physically in the Aikau source tree.
Does this file is generated during *build*? or wrongly referenced in the Page.js file.

[Link to Page.js](https://github.com/Alfresco/Aikau/blob/master/aikau/src/main/resources/alfresco/core/Page.js)

**Comment by draperd** [comment]
service/constants/Default is returned by a WebScript that is provided by the Surf framework. It is not represented by a JavaScript source file. The reason for this is that it includes applicaion context specific data that cannot be defined in a pure JS file. For example, when using service/constants/Default the application context is always correct, etc. It also includes data derived from XML configuration such as the CSRF configuration and URI templates.

Closing as not a bug.

**Comment by muralidharand** [comment]
Thanks for the information.
