### ISSUE TITLE
Can't get the dynamics value of widgets

### ISSUE THREAD

**Issue by RedRaccoon** [Alfresco/Aikau#806]
I have a webscript wich get all the workflow I wan't to show, I want to add args depending on checkbox

```
var list = {
		   name: "alfresco/lists/AlfList",		  
		   config: {
		      loadDataPublishTopic: "GET_DATA_WF",
		      loadDataPublishPayload: {
		         filtre: checkbox.config.value
		      },
		      itemsProperty: "data"
		   }
		};
var checkbox = {
		  id: "ID_CHECK",
		  name: "alfresco/forms/controls/DojoCheckBox",
		  config: {
		    fieldId: "idCheckboxGroup",
		    name: "groupFilter",
		    label: "Groupe",
		    //description: "",
		    value: "{value}",
		   // onChange:     
		  }
		};
```

In my widget (I know this code is wrong but It's for be more clear of what I would like to do)
I'm able to get the valu of the config (like name or even value) but If I change by checking or un-checking my checkbox, value won't change in my logs

```
  onGetData: function wfTab_wfTabFilter__onGetData(payload) {

    	  var url = AlfConstants.PROXY_URI+"wfTab/filter";
     
         var test = lang.getObject("filtre", false, payload);
         
      //   var checkboxValue = payload.getValue();


          this.alfLog("warn", "value of the checkbox" +checkboxValue);
```

**Comment by draperd** [comment]
Your model is being defined in a WebScript that is running on the server. The value of checkbox.config.value will be whatever it is defined in that WebScript. When the page loads that will be translated into JavaScript running on the client ... the "filtre" attribute will be fixed to whatever it was set to in the WebScript - you cannot reference a JavaScript variable defined and executed on the server from within the browser.

If you want to have list data reloaded based on a changing form control then you should look at the "alfresco/lists/AlfFilteredList" (see http://dev.alfresco.com/resource/docs/aikau-jsdoc/AlfFilteredList.html). We have examples in the unit test application that you can experiment with. See (https://github.com/Alfresco/Aikau/blob/74d632daf1ebb496e7e1240e563a654566853e43/aikau/src/test/resources/testApp/WEB-INF/classes/alfresco/site-webscripts/alfresco/lists/FilteredList.get.js)

The unit test pages for filtered list can be found at this URL (http://localhost:8089/aikau/page/tp/ws/FilteredList) once you've built and started the test application.

**Comment by RedRaccoon** [comment]
Thank you
