### ISSUE TITLE
Use Alfresco share document library full window view as an embedded content in a social intranet iframe

### ISSUE THREAD

**Issue by bgewehr** [Alfresco/Aikau#860]
Hi!

We'd like to show Alfresco Content as part of our IBM Connections social intranet since our Alfresco one service is much more accepted for enterprise sync and share than the ESN is although the features are quite similar. So we'd use the generic html widget which allows us to embed any web page into an iframe inside connections.

I could make an iframe with src=.../webdav/... show the library content but that is ugly.

We'd prefeer to show the share library as full window like it is possible in share. Is there any URL parameter to call that view in an iframe? Would you say this is a good or a bad idea?

Or should we go deeper and develop our own pages for that purpose? (Would better like to stay on the standard pages for maintenance reasons)

iframe on webdav:
![2016-02-18 09_29_38-twitter](https://cloud.githubusercontent.com/assets/4056277/13148605/4e6db7e8-d65e-11e5-9ea3-ac99576e39fa.png)

iframe on std-UI
![2016-02-18 16_51_12-twitter](https://cloud.githubusercontent.com/assets/4056277/13149051/2041abc0-d660-11e5-9140-3dcc4856c687.png)

iframe on full window tile view;
![2016-02-18 16_52_49-twitter](https://cloud.githubusercontent.com/assets/4056277/13150592/b314c7ce-d666-11e5-94d5-e345dd7427cf.png)

We'd like to use the last one within our social intranet.

Can you provide some link information on how this can be the best solution for that?

Thank you in advance!

**Comment by draperd** [comment]
Hi Bernd,

This isn't really Aikau related, but I should be able to help...

If you want to just display the existing YUI2 based Document Library that is currently found in Share then your best option is to create an extension module that removes the some of the Surf Components that make up the page. For example, the Document Library page is made up of several Surf Components rendering the header bar, the title bar, tree, filters, tags, categories and the document list and toolbar. It is fairly straightforward to create an extension module that hides the components that you don't want to see. 

If you have uses that also access Share directly then you'll want to ensure that they have the normal experience of the Document Library so you'll want to create evaluators for ensuring that this only occurs on your portal requests. 

Your final option would be (and this would be Aikau related) to create a new page that renders the Aikau version of the Document Library (however this is still in development and not production ready yet - so wouldn't be supported via normal support channels). 

This blog post describes hiding components: https://www.alfresco.com/blogs/developer/2011/07/27/how-to-hide-content-on-an-existing-alfresco-share-page/

This blog post covers some evaluation information: https://www.alfresco.com/blogs/developer/2011/07/29/sub-component-evaluations/

As this issue isn't really Aikau related though, I'm going to close it.

**Comment by bgewehr** [comment]
Thank you for your input, it helps me a lot!
