### ISSUE TITLE
FilteringSelect and MultiSelectInput form controls do not show any options to use

### ISSUE THREAD

**Issue by aviriel** [Alfresco/Aikau#904]
Aikau 1.0.39.5 + Alfresco 5.1.e.

I try to add a text field with autocomplete (or something like that) to the form dialog to select users.

The following control works good:
```
{
	name: "alfresco/forms/controls/Select",
	config: {
		fieldId: "select1",
		label: "Select a person",
		name: "select1",
		optionsConfig: {
			publishTopic: "ALF_GET_FORM_CONTROL_OPTIONS",
			publishPayload: {
				url: AlfConstants.PROXY_URI + "api/people",
				itemsAttribute: "people",
				labelAttribute: "userName",
				valueAttribute: "userName"
			}
		}
	}
}
```
So I suggest that FilteringSelect and MultiSelectInput should work in similar way, but they don't:
```
{
	name: "alfresco/forms/controls/FilteringSelect",
	config: {
		fieldId: "people1",
		name: "people1",
		label: "People",
		optionsConfig: {
			queryAttribute: "value",
			publishTopic: "ALF_GET_FORM_CONTROL_OPTIONS",
			publishPayload: {
				url: AlfConstants.PROXY_URI + "api/people",
				itemsAttribute: "people",
				labelAttribute: "userName",
				valueAttribute: "userName"
			}
		}
	}
}, {
	name: "alfresco/forms/controls/MultiSelectInput",
	config: {
		label: "people2",
		name: "people2",
		optionsConfig: {
			queryAttribute: "label",
			publishTopic: "ALF_GET_FORM_CONTROL_OPTIONS",
			publishPayload: {
				url: AlfConstants.PROXY_URI + "api/people",
				itemsAttribute: "people",
				labelAttribute: "userName",
				valueAttribute: "userName"
			}
		}
	}
}
```
FilteringSelect does not show any suggestions and always shows "The value entered in not valid", but request is sent and correct response is returned from the repository
![selection_108](https://cloud.githubusercontent.com/assets/596948/13632042/d4db8310-e5f8-11e5-801e-03b13f99c407.png)

MultiSelectInput does not even sending request and shows "Loading" all the time:
![selection_109](https://cloud.githubusercontent.com/assets/596948/13632227/aeae2822-e5f9-11e5-8c35-9633446e88ab.png)

Any ideas what to do with it? Usually I think that I do something incorrectly, but in this time Axel Faust said that it may be a bug. I copy the discussion from IRC here, maybe it can help:
<AFaust> I found why all of the widgets using ServiceStore won't work with the OptionsService (and potentially other services to load options). A bug has been introduced when some cloud related changes were included back in October. The change in question is https://github.com/Alfresco/Aikau/commit/9f082b72ace5f68d9e225e4a4944ac90bd6dc24b#diff-ef5813a119e4ee7498950e45fb286a95R395. This causes an early response (the progress pub) to the pubSub from ServiceStore providing the raw, unprocessed options. ServiceStore then unsubcribes and does not receive the actual pub payload from the OptionsService with the processed options.

**Comment by draperd** [comment]
Thanks for raising this issue as requested. I'll do some triage and then raise this as a bug in JIRA for inclusion in the next sprint. I would agree in principle that you'd expect the config to be interchangeable, we may need to make some change to the OptionsService - I'm not completely convinced your configuration is entirely correct though, but this would be an indication that the JSDoc could be improved.

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/AKU-884

**Comment by draperd** [comment]
I've done some triage and added some comments to that JIRA ticket... your configuration is missing a few attributes, but there are fundamental problems with using the OptionsService as it is now with form controls that use the ServiceStore (described in the ticket).

The purpose of the OptionsService (and the CrudService) were really to provide simple prototyping solutions for simple examples. We should be able to fix up the OptionsService so that it will at least work with these form controls, however ultimately I think you'll still be disappointed with the result because the API (and your configured use of it) doesn't provide a single "displayName" attribute. This is actually covered in depth in Tutorial 8 (https://github.com/Alfresco/Aikau/blob/master/tutorial/chapters/Tutorial8.md). What is really needed here are updates to the existing UserService to actually provide topics for retrieving user data in a more consumable fashion (i.e. with a displayName as label and userName as attribute). This service would work with the form controls you're having issues with because there wouldn't be a requirement to manipulate data at two stages. You may wish to raise an additional feature request for implementing this.

**Comment by aviriel** [comment]
Thank you! I fixed misconfiguration. But it does not help as expected. :) I'm really looking forward to your new commits and fix. After it will work, I can think how to get firstName+lastName istead of userName. I used the code from Tutorial 8, but it does not help after I moved dialog form creation from the page to the service, so now I want to make it work at list with userName.

**Comment by draperd** [comment]
As I say, I think the best approach for firstName + lastName will be for us to update the UserService. It's likely to be a commonly required capability and it will save other Community members from having to re-implement a solution. I'll raise a feature request for this.

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/AKU-886 to update the UserService. Although currently  planned for Sprint 60, there is no guarantee that it will be included in the final plan because it is an enhancement rather than a bug, but we will try to get to it as soon as possible

**Comment by aviriel** [comment]
Finally it works for me if I use custom service instead of "ALF_GET_FORM_CONTROL_OPTIONS".

Also I wrote a function to form displayName from firstName and lastName of the user in my custom service, I add it to this issue below just in case, but I'm not ready to send a pull request because I'm sure that you will not like the quality of the code. I just start to work with Aikau. If you think it's ok to add it to handle users in this way generally, please let me know, I will create a pull request to extend UserService.

```
onUsersListRequest: function sample_services_MasterDataService__onUsersListRequest(payload) {

         // Create the root URL...
         var url = AlfConstants.PROXY_URI + "api/people";

         // Update the options with a query if provided...
         var options = {};

         if (payload.query)
         {
            options.filter = payload.query;
         }

         var successFunction = lang.hitch(this, this.onUsersListRequestSuccess);

         if (url !== null)
         {
            this.serviceXhr({url: url,
                             query: options,
                             alfTopic: payload.alfResponseTopic || null,
                             alfResponseScope: payload.alfResponseScope,
                             successCallback: successFunction,
                             method: "GET"
                           });
         }
      },

      onUsersListRequestSuccess: function sample_services_MasterDataService__onUsersListRequestSuccess(response, originalRequestConfig) {
        var processedResponse = [];

        var people = response.people;
        for (var i = 0; i < people.length; i++) {
        
          processedResponse.push({
            displayName: people[i].firstName + ' ' + people[i].lastName,
            userName: people[i].userName
          });
        };
        
        this.alfPublish(originalRequestConfig.alfTopic, {
            response: processedResponse
         }, false, false, originalRequestConfig.alfResponseScope);
      },
```

**Comment by draperd** [comment]
Thanks for the update. We will still resolve the problem as originally raised. We wouldn't merge a pull request without the associated automated unit test for the changes, but your implementation does look as I would expect it to. I'm glad you've been able to resolve your issues with a custom service though.

**Comment by draperd** [comment]
I've now created a pull request to fix these issues... the unit tests associated use the Select, FilteringSelect and MultiSelectInput form controls (both scoped and unscoped) to test the OptionsService. I've also updated the UserService to provide the capability to return users with a "displayName" attribute.

There have been several fixes along the way for OptionsService as well as basic options handling in BaseFormControl. You can review the unit test page for an example of how everything can now be used successfully.

Ideally I'd like to find the time to write up the correct instructions as documentation or on a blog post but I'm unlikely to have the time in the immediate future.

Once the code has been through review and has been merged, it will be available in the 1.0.60 release next week.

**Comment by draperd** [comment]
1.0.60 has now been released with the fix - can you let us know if it resolves your issue satisfactorily please?

**Comment by aviriel** [comment]
Your solution solved all the problems. It works, so I deleted my custom service. Thank you very much!
