### ISSUE TITLE
Dojo package location prefixed by another package name ends up not loading widget / service code

### ISSUE THREAD

**Issue by AFaust** [Alfresco/Aikau#926]
This issue is very likely related to the Surf library but since it is encountered solely when using Aikau, I'm filing it here.

When multiple Dojo packages have been configured in a way where the source location of a package A is prefixed with the name of another package B, any widgets / services of package A referenced in JSON model will not work as their source code is not contained in the aggregated JS file. As far as I was able to determine via debugging, this is the result of a second, redundant package mapping process.

```xml
<config evaluator="string-compare" condition="WebFramework">
   <web-framework>
      <dojo-pages>
         <packages>
            <!-- a  package mapping ending in a location prefixed by another package name is problematic -->
            <package name="A" location="B/path/to/files" />
            <package name="B" location="js/B/path/to/files" />
         </packages>
      </dojo-pages>
   </web-framework>
</config>
```
```javascript
model.jsonModel = { widgets : [{name : 'A/moduleId'}] /* ... */ };
```
During dependency collection, the DojoDependencyHandler.getPath(String, String) operation is called to resolve a (potentially relative) module ID to the source path of the JS (or CSS, HTML, properties) file.
While outputting the aggregated dependency source, the DojoDependencyHandler.getPath(String, String) operation is called again with the already resolved source path. When the first folder in the path happens to be a name of a Dojo package, that packages location is prefixed to the already resolved path.

The result of this redundant mapping of package locations is that the DojoDependencyHandler.outputDependency(String, String, DojoDependencies) operation can't find a resource input stream for the invalid path and returns the String "null", which will be output as the "source" of the module. The output in the aggregated JS file looks like this
```javascript
'A/moduleId':function(){
null},
```

I have compiled a set of test files in the following gist: https://gist.github.com/AFaust/f1c3930c336a33e6fcb8

This was found in 5.0.d using Aikau 1.0.51 but appears to also be present in 5.0.3 (which might have had newer Spring libraries).

The example of course is using a constructed constellation, but we have actually arrived naturally in a such a situation with two separate, independant modules. Our Aikau library module defines a package "prodyna" with a location "js/prodyna" (using common Aikau root path) while our Enhanced Search module (predating Aikau and faceted search page) now defines a package "enhanced-search" with location "prodyna/enhanced-search/dojo" for a custom SearchBox widget. The location was chosen to keep all source files relating to that module in one distinct root.

A workaround exists by simply refactoring the module packages structures, but a long term solution should prevent accidental conflicts with modules not under the control of a customer / developer.

**Comment by draperd** [comment]
Yes, you're right that this isn't going to be an issue that can be resolved in any Aikau release. It will need to be addressed in a Surf update. This issue would have been better filed in JIRA than here.

In general I would like the opportunity to re-work how we configure the AMD packages via the XML configuration because we're only leveraging a small part of the capabilities that it offers.

One thing I would say that from experience mapping any package to a path starting with "js" is going to be problematic and wouldn't be recommended. I can raise a JIRA ticket in the ALF project but I'm not sure how quickly it will be prioritized to be addressed.

**Comment by AFaust** [comment]
Do you consider "js" path prefix to be problematic solely for fear of conflict with any packages that Alfresco might choose to place there? Or is there a different reason?

Since I already have a "FixedDojoDependencyHandler" sub-class of DojoDependencyHandler for ACE-5049, I'm already in the process of integrating a temporary fix for this issue there, so personally I am not affected by any lack of priority.

**Comment by draperd** [comment]
To be honest, I can't remember the exact reason... I'd have to dig into the code again, but I just know that it's been problematic in the past. I will get around to raising a JIRA issue for this and assigning to the appropriate place - I just haven't had a chance today (but this issue won't get closed until I've done it!)

**Comment by draperd** [comment]
I've raised https://issues.alfresco.com/jira/browse/ALF-21588
