### ISSUE TITLE
incomplete sentence

### ISSUE THREAD

**Issue by torstenwerner** [Alfresco/Aikau#937]
in Tutorial6.md
> The only truly important line in this file (in the context of Aikau) is the element.

it should be changed into
> ... the url element.

**Comment by draperd** [comment]
Thanks for spotting this. We'll get this changed as soon as possible. We follow the GitFlow model so fixes will be initially applied to the develop branch and then merged to master on release so you should expect to see this change in the (master branch) tutorial content from next Tuesday.

**Comment by draperd** [comment]
This has now been fixed - thanks again for raising the issue.
