### ISSUE TITLE
payload communication with "ALF_CREATE_FORM_DIALOG_REQUEST"

### ISSUE THREAD

**Issue by RedRaccoon** [Alfresco/Aikau#947]
Hello,

I have a picker and a textbox, when I select one item on picker the value go to the texbox 

but when my picker is in  a "ALF_CREATE_FORM_DIALOG_REQUEST" my payload is send but he is empty

when I click on "save" in the from dialog I'm sending payload but my function "_onPublish" is not called, I don't see a good way to do this

```
 var temp = {
 	name : "alfresco/buttons/AlfButton",
 	config : {
 		label : "old",
 		publishTopic : "ALF_CREATE_FORM_DIALOG_REQUEST",
 		publishPayloadType: "PROCESS",
 		publishPayloadModifiers: ["processCurrentItemTokens"],
 		formSubmissionPayloadMixin: this.TutorialTopic,
 		publishPayload : {
 			dialogTitle : "Create Group",
 			dialogConfirmationButtonTitle : "Create",
 			dialogCancellationButtonTitle : "Cancel",
 			formSubmissionTopic : this.TutorialTopic, // on lance ça
 			fixedWidth : true,
 			widgets : [ {
 				name : "tutorial/pickerPeople"
 			}
 
 			]
 		}
 	}
 } 
```

in the [doc ](https://dev.alfresco.com/resource/docs/aikau-jsdoc/DialogService.html#event:ALF_CREATE_FORM_DIALOG_REQUEST) I can read that formSubmissionTopic is sending the "form value" 

I have to admit I didn't really understand things like "publishPayloadType: "PROCESS" or "publishPayloadModifiers: ["processCurrentItemTokens"], 

sending payload :8ball: 
peoplePicker.js => (the button 'btn' was used when I first try to send my payload without form control) I think he sould be working even if now he is inside the form control no ?

```
 postCreate: function example_widgets_InputWidget__postCreate() {
                this.inherited(arguments);

                this.picker = new SimplePicker({
                   label: this.message("Pick user"),
                   loadDataPublishTopic: "ALF_CRUD_GET_ALL",
                   loadDataPublishPayload: {
                	   url: "api/people"
                   },
                   itemsProperty: "people",
                   itemKey: "userName",
                   propertyToRender: "userName",
                   availableItemsLabel: "available people",
                   pickedItemsLabel: "currently selected people",
                   singleItemMode: true
                });
                this.picker.placeAt(this.inputTopicNode);

                 var btn = new AlfButton({
                    label: "Publish",
                    onClick: lang.hitch(this, '_onPublish')
                });
                
                btn.placeAt(this.publishTopicNode);

            },

            _onPublish: function example_widgets_InputWidget__onPublish() {
                this.alfPublish(this.TutorialTopic, this.picker.getValue());
                this.alfLog("log", "on publie le payload");
            }
```
receving payload
label.js =>

```
postCreate: function example_widget_renderWidget__postCreate() {
                this.alfSubscribe(this.TutorialTopic, lang.hitch(this, "_onPayloadReceive"));
                
              
                this.textArea = new TextBox({
                	id: "id", 
                	fieldId: "fieldId",
                	    name: "name",
                	    label: "label",
                	    description: "description"
                 });
                this.textArea.placeAt(this.inputTopicNode);
                

                this.alfSubscribe(this.TutorialTopic, function(payload) {
                	
                });
            },

           __onPayloadReceive: function example_widgets_renderWidget__onPayloadReceive(payload) {
            	
            	try{
            	this.alfLog("log", this.textArea.setValue(payload[0].userName));
            	this.textArea.setValue(payload[0].userName);
            	}
            	catch (e){
            		this.textArea.setValue("nothing");
            		this.alfLog("log", "nothing"+e.message);
            	}
            }_

        });
```

thank you in advance

**Comment by draperd** [comment]
OK, so I think the first thing to realise is that the if you're using the ALF_CREATE_FORM_DIALOG_REQUEST topic that you're asking for a dialog that acts as a form, and that you're asking the DialogService to create the "OK"/"Cancel" buttons and the underlying form and to take responsibility for collecting all the form data.

So really you don't want to be creating a button in your form control - if you want to create a form control that is a picker then look at the alfresco/forms/controls/DocumentPicker as an example. A form control publishes its value to the form that contains it, and the form takes responsibility for controlling the overall value to be published onto a service.

I guess I'm not really sure what it is that you're trying to do - i.e. there's not a of context to the question. 

Also, to address the question of the publishPayloadType .... the idea is to be able to be able to construct payloads with data extracted from either the "currentItem" object or the widget itself - this is particularly important when declaring a payload statically but wanting to substitute in contextual data. The more frequent example of this is when defining lists where you want to have a payload that is structurally the same but draws different data from each item in the list. You don't need to set a publishPayloadType unless you want to substitute in values.

I hope this is somewhat helpful - if you could provide some more information on your overall goal then I should be able to provide some more help.

**Comment by RedRaccoon** [comment]
Hello thank you for your answer this helped me to really find my true issue with the payload, I will do my best for the explication 

Here is my context, the client want a board of workflow (something like the board in airport fly departure) and I have to add some filters, they are all good

http://www.noelshack.com/2016-12-1458740365-1.png

but as you can see, the picker for the people is not really user friendly, this is why i'm trying to use a "picker" in a popUp

here is my goal
http://www.noelshack.com/2016-12-1458740765-2.png 

Here is my code
the aikau page 

``` javascript
model.jsonModel = {
	services : [ {
		name : "alfresco/services/LoggingService",
		config : {
			loggingPreferences : {
				enabled : true,
				all : true
			}
		}
	}, "alfresco/lists/AlfList", "alfresco/services/CrudService",
			"alfresco/services/OptionsService", "tutorial/_TopicsMixin", "tutorial/pickerPeople" ],
	widgets : [
{
		name : "tutorial/labelPeople" // the form control who will be used in the alfFilteredList for filtering my board
	}

	]
};

var temp = { // my pop up
	name : "alfresco/buttons/AlfButton",
	config : {
		label : "Pick someone",
		publishTopic : "ALF_CREATE_FORM_DIALOG_REQUEST",

		publishPayload : {
			dialogTitle : "picking someone",
			dialogConfirmationButtonTitle : "Choose",
			dialogCancellationButtonTitle : "Cancel",
			formSubmissionTopic : "PUBLISH", // is a function inside pickerPeople who publish on the payload

			fixedWidth : true,
			widgets : [ {
				name : "tutorial/pickerPeople" // the widget who allow to pick
			]
		}
	}
}

model.jsonModel.widgets.push(temp);
```

For me, the formSubmissionTopic call the function "PUBLISH"


Here is my pickerPeople.js

``` javascript
define(["dojo/_base/declare",
        "dijit/_WidgetBase",
        "alfresco/core/Core",
        "dojo/_base/lang",
        "alfresco/buttons/AlfButton",
        "alfresco/forms/controls/SimplePicker",
        "tutorial/_TopicsMixin",
        "dijit/_TemplatedMixin",
        "dojo/text!./html/InputWidget.html"
    ],
    function(declare, _Widget, Core, lang, AlfButton, SimplePicker, _TopicsMixin, _Templated, template) {
        return declare([_Widget, Core, _Templated, _TopicsMixin], {

            templateString: template,
            i18nRequirements: [ {i18nFile: "./i18n/PubSub.properties"} ],

            postCreate: function example_widgets_InputWidget__postCreate() {
                this.inherited(arguments);
                
                this.alfSubscribe("PUBLISH", lang.hitch(this, '_onPublish'));
                
                
                this.textArea = new SimplePicker({ // I should have call him simplePicker to be less confusing sorry
                   label: this.message("Pick user"),
                   loadDataPublishTopic: "ALF_CRUD_GET_ALL",
                   loadDataPublishPayload: {
                	   url: "api/people"
                   },
                   itemsProperty: "people",
                   itemKey: "userName",
                   propertyToRender: "userName",
                   availableItemsLabel: "available people",
                   pickedItemsLabel: "currently selected people",
                   singleItemMode: true
                });
                this.textArea.placeAt(this.inputTopicNode);

                 var btn = new AlfButton({ // this btn help me to debbug
                    label: "Publish",
                    onClick: lang.hitch(this, '_onTry') // this function help me to debbug
                });
                
                btn.placeAt(this.publishTopicNode);

            },
            
            _onTry: function example_widgets_InputWidget__onTry() { // this function help me to debbug
            	this.alfLog("log", "tutorialtopic = "+this.TutorialTopic+" textarea.getvalue = "+this.textArea.getValue());
            },

            _onPublish: function example_widgets_InputWidget__onPublish() {

                this.alfLog("log", "tutorialtopic = "+this.TutorialTopic+"this.textArea.getvalue = "+this.textArea.getValue());
                this.alfLog("log", "on publie le payload");
                this.alfPublish(this.TutorialTopic, this.textArea.getValue()); // the function who send the payload to the topic
            }

        });
});

```

For me, when I'll click "choose" on my picker, he will call onPublish and send the payload on the topic "this.TutorialTopic"

 wich is defined here in the _TopicsMixin.js

``` javascript
define(["dojo/_base/declare"],
    function(declare) {

        return declare(null, {
            TutorialTopic: "ALFRESCO_TUTORIAL_TOPIC"
        });
    });
```

and for finishing, my labelPeople.js who will receive the payload

``` javascript
define(["dojo/_base/declare",
        "dijit/_WidgetBase",
        "alfresco/core/Core",
        "dojo/_base/lang",
        "alfresco/forms/controls/TextBox",
        "tutorial/_TopicsMixin",
        "dojo/dom-construct",
        "dijit/_TemplatedMixin",
        "dojo/text!./html/InputWidget.html"
    ],
    function(declare, _Widget, Core, lang, TextBox, _TopicsMixin, domConstruct, _Templated, template) {
        return declare([_Widget, Core, _TopicsMixin, _Templated], {

            templateString: template,
            i18nRequirements: [ {i18nFile: "./i18n/PubSub.properties"} ],

            buildRendering: function example_widgets_renderWidget__buildRendering() {
                this.renderWidgetHeading = this.message('renderWidget.heading');
                this.inherited(arguments);
            },

            postCreate: function example_widget_renderWidget__postCreate() {
                this.alfSubscribe(this.TutorialTopic, lang.hitch(this, "_onPayloadReceive"));                
              
                this.textArea = new TextBox({ //this is random id, label and description
                	id: "icila", 
                	fieldId: "EMAIL",
                	    name: "email",
                	    label: "Contact",
                	    description: "Your e-mail address"
                 });
                this.textArea.placeAt(this.inputTopicNode);
                

                this.alfSubscribe(this.TutorialTopic, function(payload) { // the subscribing method to the topic
             
                	
                });
            },

            _onPayloadReceive: function example_widgets_renderWidget__onPayloadReceive(payload) {
            	
            	try{
            		console.log(payload[0].userName);
            	this.alfLog("log", this.textArea.setValue(payload[0].userName));
            	this.textArea.setValue(payload[0].userName);
            	}
            	catch (e){
            		this.textArea.setValue("rien reçue"); //mean "nothing received"
            		this.alfLog("log", "rien reçue"+e.message);
            	}
            }

        });
    });
```



And here is my problem (I will use pictures)

(dont mind on the "
http://image.noelshack.com/fichiers/2016/12/1458742773-3.png

When I click on "choose" my pickerPeople.js is actually sending an empty payload and the next logs are because he is receving nothing

This is strange because, when I click on the function onTry (the function were i wrote "for debbug") I can see the payload

``` javascript
 _onTry: function example_widgets_InputWidget__onTry() {
            	this.alfLog("log", "tutorialtopic = "+this.TutorialTopic+" textarea.getvalue = "+this.textArea.getValue());
            	this.alfPublish(this.TutorialTopic, this.textArea.getValue());
            },
```

http://www.noelshack.com/2016-12-1458743359-4.png

we can see that he is able to get the payload, but in this case the onPaylodReceived is not called on the labelPeople ...  I my understanding of aikau this should work because if I don't use pubscope the topic listen everywhere 

and for me the most confusing, when I just put the pickerPeople and labelPeople close (I mean not inside a pop up)

``` javascript
{
		name : "tutorial/labelPeople"
	},
	{
		name : "tutorial/pickerPeople"
	}
```

http://www.noelshack.com/2016-12-1458743903-5.png 

it's working ... and it's the same if i put the labelPeople inside the same popup of the pickerPeople

I have spent a lot of time on my problem and I think there is just something that I still don't know/ don't understand, thank you in advance, hoping this could help other people

**Comment by draperd** [comment]
Apologies for not getting back to you yesterday on this - we've been very busy recently !

As a brief aside, if we can go back to the requirements a little bit, I'd like to understand why you want to use the SimplePicker rather than say the FilteringSelect? This is more so that I can understand any improvements we need to make in this area. I think what would be ideal would be to have a dedicated user picker (which is something we've actually had on our backlog for some time, see https://issues.alfresco.com/jira/browse/AKU-146). There is also the MultiSelectInput widget and we recently did some work in this area with regards to user selection (see #904). As of 1.0.60 you should at least be able to make use of the improvements to the `alfresco/services/UserService` to get user display names without going through the CrudService.

To go back to your main issue... I think what you might want to do is go combine your TextBox and PeoplePicker into a single form control (which is possibly what you're trying to do already). My assumption is that you don't want users to be able to enter text into the text box - it is purely for display purposes only? Again, this is somewhat similar to the `alfresco/forms/controls/DocumentPicker` - you could use this as a template for your form control and would just need to swap out the `alfresco/pickers/Picker` from the `widgetsContent` array. This takes care of both the display after selection as well as the dialog popup for selection.

Looking at your first screenshots are you wanting to use all these form controls as filters in an AlfFilteringList? This would certainly make sense. I can't help thinking that really what is required is a decent people picker control that you can re-use. 

Hopefully this is of some help - I appreciate that I'm not providing any coding solutions so far - what you've provided is very useful in understanding your objectives though. So to summarize my questions/points:

* Can you explain why you want a pop-up rather than a simple user picker form control - or would a simple user picker (as some form of drop-down) be a better solution?
* Try out the updated UserService for getting user data (so you can have userName as value, displayName as label)
* Try to combine the textbox/picker into a single form control - look at the `alfresco/forms/controls/DocumentPicker` as one example of doing this, but there other ways too. Having separate controls here is probably not the right approach

**Comment by RedRaccoon** [comment]
Thank you for your answer I worked on your propositions 

1 ) I wanted the pop up just for esthetic reasons, he looked cool and as he is too big to go on the top on my board I tought in the pop up  was a good idea

3 ) Like you said I will try with a transformation of the DocumentPicker I looked inside the .js and I think this will exactly what I have to do, today I also worked on making a SimpleFilteredPicker (trying to mix the idea of alfFilteredList and SimplePicker)
I really will try to do both because once you succed to do something in Aikau it's really easy to re-use  

Thanks again your post do helped me !
