### ISSUE TITLE
AlfTabContainer + AlfList

### ISSUE THREAD

**Issue by aviriel** [Alfresco/Aikau#957]
If I create a new tab in AlfTabContainer using tabAdditionTopic and a tab contains AlfList, then the list is not rendered (shows alflist.no.data.message) until I select another tab and then select again this newly created tab. Any way to solve it?

```
var tabs = {
   name: "alfresco/layout/AlfTabContainer",
   config: {
      tabSelectionTopic: "SELECT_TAB_TOPIC",
      tabDisablementTopic: "DISABLE_TAB_TOPIC",
      tabAdditionTopic: "ADD_TAB_TOPIC",
      tabDeletionTopic: "DELETE_TAB_TOPIC",
      widgets: []
   }
};

var newTab = {
   widgets: [{
      name: "alfresco/lists/AlfList",
      title: "Title",
      config: {
         loadDataPublishTopic: "ALF_CRUD_GET_ALL",
         loadDataPublishPayload: {
            url: "api/groups?sortBy=displayName&zone=APP.DEFAULT"
         },
         itemsProperty: "data",
         widgets: [{
            name: "alfresco/lists/views/AlfListView",
            config: {
               widgets: [{
                  name: "alfresco/lists/views/layouts/Row",
                  config: {
                     widgets: [{
                        name: "alfresco/lists/views/layouts/Cell",
                        config: {
                           widgets: [{
                              name: "alfresco/renderers/Property",
                              config: {
                                 propertyToRender: "displayName"
                              }
                           }]
                        }
                     }]
                  }
               }]
            }
         }]
      }
   }]
};

var AddButton = {
   name:"alfresco/buttons/AlfButton",
   config: {
      label: "Add tab",
      publishTopic: "ADD_TAB_TOPIC",
      publishPayload: newTab
   }
}
```

**Comment by AFaust** [comment]
@aviriel The AlfList normally waits for the page load event to load its initial batch of data. This is triggered only when the tab is changed. You may want to configure your AlfList using the "waitForPageWidgets" property set to "false" so it loads its data immediately when the widget processing has been completed.

**Comment by draperd** [comment]
Yes, @AFaust is correct. If you're starting to work with the AlfTabContainer - you may also want to be aware of the "delayProcessing" configuration attribute (see http://dev.alfresco.com/resource/docs/aikau-jsdoc/AlfTabContainer.html) by default the tab container won't attempt to render the content of any tab that is not visible (for performance reasons). However, you can change this behaviour on a tab-by-tab basis by configuration "delayProcessing" to be false.

If @AFaust's suggestion resolves your problem could you please close this issue or update it to indicate if you believe there to be a bug that requires fixing.

**Comment by aviriel** [comment]
Yes, it helps if I use both waitForPageWidgets:false for AlfList and delayProcessing:false for TabContainer. Thank you!
