### ISSUE TITLE
Aikau - Google Chrome

### ISSUE THREAD

**Issue by patricia93sousa** [Alfresco/Aikau#983]
I'm trying to use some features of your code but, the aikau pages doesn't work on Chrome? In FireFox I open the page and works, but in Chrome doesn't work.

**Comment by draperd** [comment]
You need to be much, much more specific about your actual problem. We run cross browser unit testing (which includes Chrome) and I do the majority of my development against Chrome as a primary browser so I know that it works on Chrome. What specifically is the problem that you're encountering?

**Comment by draperd** [comment]
Closing due to lack of information - please re-open if you have a specific problem with out-of-the-box Aikau widgets.

**Comment by patricia93sousa** [comment]
The preview Aikau does not supports digital signatures.

**Comment by draperd** [comment]
This is because there isn't a PDF.js release that supports digital signatures.

**Comment by patricia93sousa** [comment]
The new versions supports digital signatures... The own Alfresco uses
pdf.js in the document details that shows the digital signatures. Aikau
doesn't use the version of the pdf.js of the document details.




Patrícia Sousa

2016-04-28 13:29 GMT+01:00 Dave Draper <notifications@github.com>:

**Comment by draperd** [comment]
Versions or stable releases?

**Comment by patricia93sousa** [comment]
I suppose that Alfresco uses stable versions in the document-details.



Enviado com MailTrack
<https://mailtrack.io/install?source=signature&lang=pt&referral=patriciarvsousa@gmail.com&idSignature=24>

Patrícia Sousa

2016-05-03 11:15 GMT+01:00 Dave Draper <notifications@github.com>:

**Comment by draperd** [comment]
The document details page doesn't use Aikau at all.

**Comment by patricia93sousa** [comment]
I know but the previewer of the document-details can't be integrated in the
Aikau?




Enviado com MailTrack
<https://mailtrack.io/install?source=signature&lang=pt&referral=patriciarvsousa@gmail.com&idSignature=24>

Patrícia Sousa

2016-05-03 11:18 GMT+01:00 Dave Draper <notifications@github.com>:

**Comment by draperd** [comment]
These are two entirely different things.... PDF.js is used in both the document-details page in Share (which is a YUI2 based page) and for a separate plugin used in the AlfDocumentPreview widget - although they both use PDF.js they are **not** the same thing.

**Comment by patricia93sousa** [comment]
So, the problem is not of the pdf.js then?



Enviado com MailTrack
<https://mailtrack.io/install?source=signature&lang=pt&referral=patriciarvsousa@gmail.com&idSignature=24>

Patrícia Sousa

2016-05-03 11:44 GMT+01:00 Dave Draper <notifications@github.com>:

**Comment by draperd** [comment]
We upgraded the version that Aikau uses, and have updated the version that Alfresco uses in the document-details page... it has been released in Aikau (because it is on weekly releases) but not the version in Alfresco (because it is on a much longer release cycle).
