### ISSUE TITLE
_valueChangeOf_ BaseFormControl not published when inside ControlRow on Form processing completion

### ISSUE THREAD

**Issue by johhnywishwash** [Alfresco/Aikau#987]
I have a problem where the value of any form control extended from **_BaseFormControl_** does not publish its value once the form widgets have been processed if it is inside the **_ControlRow_** widget.  

In a form I was working on I wanted to show/hide form controls based upon the value of another control. I noticed the visibilityConfig rules stopped working on the controls placed within the **_ControlRow_**.  After looking at the pub/sub log I could see that the controls inside the **_ControlRow_** were not publishing to the _valueChangeOf_ topic when the page loaded.

After walking through what was happening in the javascript debugger console I have discovered that the **_BaseFormControl_** widgets inside the **_ControlRow_** create deferred objects with their **_publishValue: function alfresco_forms_controls_BaseFormControl__publishValue_** function.  However they are never resolved as this occurs after the **_onWidgetAddedToDocument: function alfresco_forms_controls_BaseFormControl__onWidgetAddedToDocument_** function is called in which the resolution of the deferredValuePublication property the deferred objects were set to is executed.

The issue seems to come from that the **_publishChildValue: function alfresco_forms_LayoutMixin__publishChildValue_** function is called after the child widget has executed the **_onWidgetAddedToDocument: function alfresco_forms_controls_BaseFormControl__onWidgetAddedToDocument_**

I have created a test page with the following widgets to demonstrate the issue:

```
{
	name : "alfresco/forms/Form",
	config : {
		id : "FORM_WITHOUT_CONTROL_ROW",
		okButtonPublishTopic : "SAVE_FORM_WITHOUT_CONTROL_ROW",
		okButtonLabel : "Save Form 1",
		widgets : [
				{
					name : "alfresco/forms/controls/CheckBox",
					config : {
						fieldId : "control_a",
						name : "control_a",
						label : "Control A",
						description : "When selected this should show the field Control B",
						value : true
					}
				},
				{
					name : "alfresco/forms/controls/TextBox",
					config : {
						fieldId : "control_b",
						name : "control_b",
						label : "Control B",
						description : "This should be shown when check box Control A is checked",
						visibilityConfig : {
							initialValue : false,
							rules : [ {
								targetId : "control_a",
								is : [ true ]
							} ]
						}
					}
				}, {
					name : "alfresco/forms/controls/TextBox",
					config : {
						fieldId : "control_c",
						name : "control_c",
						label : "Control C"
					}
				}, {
					name : "alfresco/forms/controls/TextBox",
					config : {
						fieldId : "control_d",
						name : "control_d",
						label : "Control D"
					}
				} ]
	}
},
{
	name : "alfresco/forms/Form",
	config : {
		id : "FORM_WITH_CONTROL_ROW",
		okButtonPublishTopic : "SAVE_FORM_WITH_CONTROL_ROW",
		okButtonLabel : "Save Form 2",
		widgets : [
				{
					name : "alfresco/forms/ControlRow",
					config : {
						title : "Control Row For Controls E & F",
						widgets : [
								{
									name : "alfresco/forms/controls/CheckBox",
									config : {
										fieldId : "control_e",
										name : "control_e",
										label : "Control E",
										description : "When selected this should show the field Control F",
										value : true
									}
								},
								{
									name : "alfresco/forms/controls/TextBox",
									config : {
										fieldId : "control_f",
										name : "control_f",
										label : "Control F",
										description : "This should be shown when check box Control E is checked",
										visibilityConfig : {
											initialValue : false,
											rules : [ {
												targetId : "control_e",
												is : [ true ]
											} ]
										}
									}
								} ]
					}
				}, {
					name : "alfresco/forms/controls/TextBox",
					config : {
						fieldId : "control_g",
						name : "control_g",
						label : "Control G"
					}
				}, {
					name : "alfresco/forms/controls/TextBox",
					config : {
						fieldId : "control_h",
						name : "control_h",
						label : "Control H"
					}
				} ]
	}
},
{
	name : "alfresco/forms/Form",
	config : {
		id : "FORM_WITH_CONTROL_ROW_ALL_WIDGETS_INSIDE",
		okButtonPublishTopic : "SAVE_FORM_WITH_CONTROL_ROW_ALL_WIDGETS_INSIDE",
		okButtonLabel : "Save Form 3",
		widgets : [ {
			name : "alfresco/forms/ControlRow",
			config : {
				title : "Control Row For Controls I,J,K,L",
				widgets : [
						{
							name : "alfresco/forms/controls/CheckBox",
							config : {
								fieldId : "control_i",
								name : "control_i",
								label : "Control I",
								description : "When selected this should show the field Control J",
								value : true
							}
						},
						{
							name : "alfresco/forms/controls/TextBox",
							config : {
								name : "control_j",
								label : "Control J",
								description : "This should be shown when check box Control I is checked",
								visibilityConfig : {
									initialValue : false,
									rules : [ {
										targetId : "control_i",
										is : [ true ]
									} ]
								}
							}
						}, {
							name : "alfresco/forms/controls/TextBox",
							config : {
								fieldId : "control_k",
								name : "control_k",
								label : "Control K"
							}
						}, {
							name : "alfresco/forms/controls/TextBox",
							config : {
								fieldId : "control_l",
								name : "control_l",
								label : "Control L"
							}
						} ]
			}
		} ]
	}
}
```

I have tested this issue out in Safari 9.1 and Google Chrome 49.0.2623.110

**Comment by draperd** [comment]
What version of Aikau are you using?

**Comment by draperd** [comment]
I've created a test page using the model you've provided (against 1.0.62) and I see the Control F appearing/disappearing as you check and uncheck control E. I also see Control J appearing/disappearing as you check and uncheck Control I. This is what I believe you're expecting to see.

I'm assuming that you're probably using a version of Aikau shipped with an Alfresco release rather than picking a more recent release. I think that the PR #414 (and possibly #421) have addressed this issue. 

If you could try a more recent release then I think that it will resolve your issue.

**Comment by johhnywishwash** [comment]
1.0.39.5 (the version in Alfresco 5.1 Enterprise)

Yeah thanks!  Just realised i was testing this on the alfresco aikau version!  Tested it out on 1.0.62 and it all works fine!

**Comment by draperd** [comment]
OK... cool, I'll close this issue then - thanks for updating the ticket
