### ISSUE TITLE
Errors refreshing web scripts with two or more Aikau JARs in Share

### ISSUE THREAD

**Issue by AFaust** [Alfresco/Aikau#988]
During my tests and change "liberation" in the context of #958 I noticed that two Aikau web scripts cause errors during web script refreshs (and initial Share startup) due to having URL conflicts with web scripts from an earlier Aikau release.

Broken Web Scripts
03110005 Web Script document org/alfresco/aikau/1.0.61/webscripts/sanitize-response.get.desc.xml is attempting to define the url '/sanitize/response:GET' already defined by org/alfresco/aikau/sanitize-response.get.desc.xml (classpath:alfresco/site-webscripts/org/alfresco/aikau/1.0.61/webscripts/sanitize-response.get.desc.xml)
03110004 Web Script document org/alfresco/aikau/1.0.61/webscripts/sanitize-data.post.desc.xml is attempting to define the url '/sanitize/data:POST' already defined by org/alfresco/aikau/sanitize-data.post.desc.xml (classpath:alfresco/site-webscripts/org/alfresco/aikau/1.0.61/webscripts/sanitize-data.post.desc.xml)

This was found running Alfresco 5.0.3 with a local Aikau 1.0.61 build (from my branch [Aikau-958](https://github.com/AFaust/Aikau/tree/Aikau-958)) while 1.0.52 and 1.0.60 JARs were also deployed in the web app. Both 1.0.52 and 1.0.60 include the sanitize-response.get.desc.xml in the same path (without a version identifier) and only the introduction of the version identifier in the path for 1.0.61 now causes the conflict. Previously the (undefined / arbitrary) load order of the classpath prevented this issue. The URL of those web scripts should probably include the version identifier as well to avoid such issues when multiple Aikau JARs are present.

**Comment by draperd** [comment]
Yes, I'm aware of this issue - it shouldn't actually cause any issues (because those WebScripts are identical) - however, it's something I haven't gotten around to fixing it. I'll try and get it done asap.

**Comment by draperd** [comment]
This is now resolved in the 1.0.63 release (unless of course you're using a combination of any release from 1.0.17 to 1.0.59 with any release between 1.0.60 and 1.0.62).
